### ISSUE TITLE
Enhanced Binding Intellisense

### ISSUE THREAD

**Issue by dansiegel** [mfractor/mfractor-feedback#10]
# Description

There are certain edge cases where the BindingContext does not match the ViewModel of the View/Page. An example of this is when working with a DataTemplate in a ListView, the BindingContext for the cell is the model object from the ItemSource, and not the ViewModel. In this case a normal binding does not work, and the intellisense does not work.

## Sample

```xaml
<ListView ItemSource="{Binding Monkeys}">
  <ListView.ItemTemplate>
    <DataTemplate>
      <TextCell Text="{Binding Name}">
        <TextCell.ContextActions>
          <MenuItem Text="Delete" 
                    IsDestructive="true"
                    Command="{Binding DeleteCommand}" 
                    CommandParameter="{Binding .}" />
        </TextCell.ContextActions>
      </TextCell>
    </DataTemplate>
  </ListView.ItemTemplate>
</ListView>
```

In this sample the `DeleteCommand actually comes from the ViewModel not the Monkey model... so it should be updated to something like:

```xaml
<ListView ItemSource="{Binding Monkeys}"
          x:Name="listView">
  <ListView.ItemTemplate>
    <DataTemplate>
      <TextCell Text="{Binding Name}">
        <TextCell.ContextActions>
          <MenuItem Text="Delete" 
                    IsDestructive="true"
                    Command="{Binding BindingContext.DeleteCommand,Source={x:Reference listView}}" 
                    CommandParameter="{Binding .}" />
        </TextCell.ContextActions>
      </TextCell>
    </DataTemplate>
  </ListView.ItemTemplate>
</ListView>
```

**Comment by matthewrdev** [comment]
Thanks for the request @dansiegel.

I'm thinking that a code fix would be the best solution for this.

As MFractor already discovers and analyses bindings, I can extend the binding expression analyser and have it try to resolve the command on the page-level binding context. If it finds a match, it'd suggest a code fix that transforms the binding expression in example one into the expression in example two.

Would that work?
