### ISSUE TITLE
Go-To Xaml Symbol (cmd+D) incorrect work for nested markup attributes in XAML 

### ISSUE THREAD

**Issue by mrxten** [mfractor/mfractor-feedback#101]
Shown in video, please check too.

For example I cannot go to converter inside binding
[Screen Recording 2019-02-21 at 13.34.18.mov.zip](https://github.com/mfractor/mfractor-feedback/files/2888877/Screen.Recording.2019-02-21.at.13.34.18.mov.zip)

**Comment by matthewrdev** [comment]
Thanks for reporting this @mrxten. This was originally by-design to save development time however you are absolutely correct that it's wrong.

I'll aim to include this in the 3.7.10 release.

**Comment by matthewrdev** [comment]
@mrxten With the introduction of the new XAML editor in Visual Studio Mac 8.2 this is now natively supported by the editor. We are deprecating our support for the old editor in MFractor v3.9 so I'm closing this issue.
