### ISSUE TITLE
Automatically set ViewModel as BindingContext on generated View/ViewModel

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#103]
When generating a View/ViewModel it would be great if the ViewModel was already set as the binding context of the view.

There are various ways to set the binding context so it would probably need a few options or it will mess with people's coding styles. I'm mainly interested in option A but if you add that then people will probably want MVVM FrameWork and code behind support. Choosing which option would be optional and would be done from a drop down in the wizard.

Option A - Set BindingContext in XAML
The ViewModels Name Space is declared in XAML and binding context is set on the context page.
e.g.
![screen shot 2019-02-23 at 8 48 30 am](https://user-images.githubusercontent.com/29908924/53273523-56815400-3748-11e9-8366-20de3d3ce80e.png)

Option B - Set In Code
Adds a property to the page called ViewModel, sets as the binding context, adds the using directive.
e.g.
![screen shot 2019-02-23 at 8 42 59 am](https://user-images.githubusercontent.com/29908924/53273110-40bf5f00-3747-11e9-8c2e-c95fe7ab626c.png)

Option C,D,E... - Register View/ViewModel in MVVM Framework
Registers the View/ViewModel pair with the selected FrameWork, this could be tricky to work out where to do it and will be slightly different for each framework.

**Comment by matthewrdev** [comment]
Thanks for reporting this Lachlan, I've also had other customers bring up this suggestion.

This will be included in the 3.7.10 release (which will also include a streamlined Mvvm Wizard UI design).

**Comment by lachlanwgordon** [comment]
Excellent, I look forward to it. Let me know if you need a tester or someone to bounce ideas off.

**Comment by dansiegel** [comment]
This needs to factor in Prism where this would be a terrible idea... you can explicitly set the ViewModelLocator.AutowireViewModel to true if you want but it's not actually required.

**Comment by matthewrdev** [comment]
@dansiegel By default, this will be turned off. It will also be driven by Prisms framework configuration that's bundled into MFractor.

Say the user did want to use some kind of auto-wire up for Prism, what is the best way for us to support?

**Comment by dansiegel** [comment]
depends slightly on whether it's Prism 7.2 or older... in 7.2 we have support for XF's XmlnsDefintionAttribute... 

```xml
<ContentPage xmlns:prism="http://prismlibrary.com"
             prism:ViewModelLocator.AutowireViewModel="True">
```

The older fully qualified version would be:

```xml
<ContentPage xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True">
```

The only time it's actually required is when the Page is explicitly set as a child of a TabbedPage since anything handled by the NavigationService will automatically handle setting that property to true.

**Comment by matthewrdev** [comment]
![image](https://user-images.githubusercontent.com/3260473/53459127-6076c000-3a84-11e9-8561-30b03d74aa36.png)

This is how the chooser will appear in the Projects MVVM settings. For v1 this will include option A and B as outlined by @lachlanwgordon .

**Comment by matthewrdev** [comment]
@dansiegel Based on what you are describing, we do not need to add any kind of initialisation for Prism. Users will most likely need to manually hook it up based on particular use-cases. Is this correct?

**Comment by matthewrdev** [comment]
Completed and available in 3.7.10. We support the Option A and Option B variants.

We've released two v3.7.10 build so if the binding context initialisation isn't available, uninstall and then re-install to get the latest build.

**Comment by dansiegel** [comment]
@matthewrdev there would be two variants....

1) They want to explicitly opt-out of having the ViewModelLocator Autowire
2) They specifically need to opt-in due to the page being a hard coded child of a MultiPage<T>

**Comment by matthewrdev** [comment]
Available in v3.7.10 of MFractor for Visual Studio for Mac.

![image](https://user-images.githubusercontent.com/3260473/53598746-9b4e3480-3bf9-11e9-8496-d9b69c3fbce4.png)

**Comment by matthewrdev** [comment]
@dansiegel As I understand, we'd need to add two Prism variants like so:
 
1. Prism: Do Not Autowire Binding Context
```
<ContentPage xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="false">
```

2. Prism: Explicit Autowire Binding Context
```
<ContentPage xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="true">
```

Is this correct?

**Comment by dansiegel** [comment]
You could account for the default:

3. Prism: Implicit Autowire Binding Context

```xml
<ContentPage>
```

but otherwise yes...

**Comment by matthewrdev** [comment]
Thanks for the quick feedback! Option 3 (as outlined above) would be covered by the default `No Binding Context Initialisation`, however, it may be worth including an option for Prism.

So three options?

1. Prism: Do Not Autowire Binding Context
2. Prism: Explicit Autowire Binding Context
3. Prism: Implicit Autowire Binding Context

**Comment by dansiegel** [comment]
I might word it Opt-Out instead of Do Not... but yes
