### ISSUE TITLE
Refactoring action to Extend Control With Renderer

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#104]
In the refactor options for any control there would be an option to "Extend Control With Renderer".

This would prompt for details similar to the "Extract XAML Control" but with additional fields to set the folder for the locations of renderers on each platform.

The Control will automatically extend the control that you right clicked on and have the appropriate namespaces
e.g.
![screen shot 2019-02-23 at 10 01 13 am](https://user-images.githubusercontent.com/29908924/53276141-05765d80-3752-11e9-907a-e270f04bdc35.png)

The Renderers in each project extends the appropriate renderer, adds the ExportRenderer Attribute and the appropriate using directives.
![screen shot 2019-02-23 at 9 52 04 am](https://user-images.githubusercontent.com/29908924/53275823-b54acb80-3750-11e9-9498-3dc7f461a5f5.png)

The Xaml will be updated to use the new control
![screen shot 2019-02-23 at 10 01 33 am](https://user-images.githubusercontent.com/29908924/53276151-0effc580-3752-11e9-87d9-7e1779cf8ee5.png)

**Comment by matthewrdev** [comment]
While we don't have this exact feature available (yet), we do have the [Generate Custom Renderers](http://docs.mfractor.com/code-actions/csharp/forms/#generate-custom-renderers)feature that you could use in the meantime.

To use, press `Option+Return` over a control declaration in C# and choose `Generate Custom Renderers`.

**Comment by lachlanwgordon** [comment]
Oh excellent. That’ll keep me happy.

**Comment by matthewrdev** [comment]
@lachlanwgordon Closing this as our generate renderers code action accomplishes this: https://docs.mfractor.com/xamarin-forms/custom-renderers/generate-custom-renderers/
