### ISSUE TITLE
Redesign and simplify the MVVM wizard.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#105]
After speaking to many customers about the MVVM wizard, the v1, while loved, is clunky, overcomplicated and difficult to use.

The main complaints:
 * Too many options.
 * Does not connect the binding context to the view.
 * User interface is too complicated.

Following from these feedback items, the MVVM wizard is being re-designed to simplify it. The wizard will become a single text entry for the feature name with a preview for the XAML view and the view model:

![image](https://user-images.githubusercontent.com/3260473/53378082-1a502c80-39b0-11e9-8ea8-e14b126b647f.png)

Users can access all their project MVVM settings through the **Settings** button.

**Comment by matthewrdev** [comment]
Completed and will be available in 3.7.10. Should be released by Friday 1st of March.

![image](https://user-images.githubusercontent.com/3260473/53389285-6e700680-39da-11e9-9e75-0795a1c4f643.png)

**Comment by matthewrdev** [comment]
See: https://twitter.com/matthewrdev/status/1100264709456982018

**Comment by lachlanwgordon** [comment]
Is that screen shot on the wrong issue?

**Comment by lachlanwgordon** [comment]
Looks good, generating from xaml is especially cool from shell.

Does the preview on the left let you choose between previewing xaml and xaml.cs?

**Comment by lachlanwgordon** [comment]
Will the settings be preserved so each time I create another View/ViewModel it does the same thing?

My standard scenario would be:
 - The first time I use the wizard I tell it to put my views in Views and ViewModels in ViewModels and that I would like them linked(when that feature is ready) and select a base class.
 - Each subsequent time I use it the settings are the same so I rarely have to open settings.

Most of these settings would make sense at the project/solution level but it would be cool if where possible it carries over to new solutions.

**Comment by matthewrdev** [comment]
Yes, the settings are persisted for the project. They are saved when you hit "Save" in the settings dialog and restored each time you open the MVVM Wizard.

You can also choose between the XAML view and code behind when in the Wizard.

**Comment by matthewrdev** [comment]
Bumping this into the 3.7.10 release as it's a major UX upgrade and there are many other enhancements to the product we want to release. Should be out within the next 1-2 days.
