### ISSUE TITLE
Extension Not Available in Visual Studio 2019 Preview 2

### ISSUE THREAD

**Issue by SharpMobileCode** [mfractor/mfractor-feedback#106]
I downloaded Visual Studio for Mac 2019 Preview 2.  I went to add the MFractor extension, but it appears that MFractor is not included in the list.  However, it's still available from my Visual Studio 2017 for Mac install.  Sounds like some sort of compatibility issue?  Could this me made available for Visual Studio 2019 Preview 2?  XAML intellisense in VS2019 is still horrible so I would love to use MFractor :)

**Comment by matthewrdev** [comment]
Hi @SharpMobileCode.

We've been holding off publishing a build into for the 2019 Preview as there have been breaking API changes in each release.

That said, I'm getting this request more and more so we'll try to get a build up next week. I'll let you know when it's available.

**Comment by matthewrdev** [comment]
MFractor is now available for Visual Studio for Mac 2019:

![image](https://user-images.githubusercontent.com/3260473/53772228-b8586f80-3f39-11e9-8728-6d48544c3cba.png)

To install, please open the **Extension Manager**, go to **Gallery** and click **Refresh**. MFractor (3.7.10) should appear under **IDE Extensions**.
