### ISSUE TITLE
Settings for Format Document / Feedback

### ISSUE THREAD

**Issue by madrvojt** [mfractor/mfractor-feedback#107]
It will be great if i have access to Format Document settings. 

Examples for settings:
a) 
If i used format document integrated in VS4Mac, i will have 4 whitespaces (before text).

http://prntscr.com/mz6rwn

When I used mFractor formatter , there is only 2 whitespaces. I want set this value to 4.

http://prntscr.com/mz6s58

b) Ability to set different formatting namespaces and rest of the page.

Something line this - http://prntscr.com/mz6tos

Thanks Matthew :)

**Comment by matthewrdev** [comment]
@madrvojt Whitespace formatting options have been added as of MFractor v3.8.2. Please upgrade and head to *Preferences* -> *MFractor* -> *Formatting* to control MFractors whitespace settings.
