### ISSUE TITLE
Generate View/Viewmodel in different projects

### ISSUE THREAD

**Issue by WouterStraver** [mfractor/mfractor-feedback#108]
It would be nice to use the mvvm wizard when using a separate project for my viewmodels. This is already possible with the navigation between pages/viewmodels

**Comment by matthewrdev** [comment]
Thanks for the feedback Wouter. I have started implementing this now.

**Comment by matthewrdev** [comment]
This has been completed and will be available in MFractor 3.8.1.

![image](https://user-images.githubusercontent.com/3260473/57120500-3bb90480-6db5-11e9-9d6f-407f87162c0d.png)

**Comment by WouterStraver** [comment]
Awesome work! Thanks a lot!

**Comment by matthewrdev** [comment]
Completed and available in MFractor v3.8.1.
