### ISSUE TITLE
Generate resources localization in different projects

### ISSUE THREAD

**Issue by WouterStraver** [mfractor/mfractor-feedback#109]
It would be nice to be able to generate resx files in another project.

**Comment by matthewrdev** [comment]
This is a great idea Wouter, I'll add this into the backlog for our next release.

**Comment by WouterStraver** [comment]
I was wondering if there was any progress on this request :-)

**Comment by matthewrdev** [comment]
Hey Wouter, apologies but there was no movement on this. We got caught up in MFractor for Windows.

![image](https://user-images.githubusercontent.com/3260473/62600222-ac7e3880-b931-11e9-9134-9b62dd83a6dc.png)

Would a project combo box just above the Resource file picker be suitable?

**Comment by WouterStraver** [comment]
No worries, you already did an awesome job the last months! 

Yes a project combo box would be great. 

Thanks for the quick reply :-)

**Comment by matthewrdev** [comment]
@WouterStraver This has been released in v3.8.19 of MFractor.

You should receive an update notification, however, you can also download and install using this file:
http://addins.monodevelop.com/Stable/Mac/8.3.1/MFractor.VS.Mac.MFractor-3.8.19.mpack
