### ISSUE TITLE
StaticResource InteliSense doesn't work with PrismApplication

### ISSUE THREAD

**Issue by rotorgames** [mfractor/mfractor-feedback#110]
I have App.xaml file with resources which inherits PrismApplication class in my project. I found that StaticResource tips don't work in XAML because of it.

**Comment by rotorgames** [comment]
@matthewrdev Any updates?

**Comment by matthewrdev** [comment]
@rotorgames Thanks for the reminder, have let this stagnate.

Can you please provide a small repro case again? I've lost the last one :|

**Comment by rotorgames** [comment]
@matthewrdev I'm sorry but it didn't help :(

**Comment by matthewrdev** [comment]
@rotorgames Can you provide a small reproduction sample?

**Comment by matthewrdev** [comment]
@rotorgames Just another nudge, can I please grab a reproduction sample?

**Comment by matthewrdev** [comment]
@rotorgames This issue has gone stale and am closing. If it's still present, please re-open it and attach a small reproduction case.
