### ISSUE TITLE
UI Glitch when deleting images

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#111]
Today when I deleted an image by right click, delete image.jpg I got this strange dialog with no chrome around it.

![Screen Shot 2019-06-11 at 4 53 00 pm](https://user-images.githubusercontent.com/29908924/59269592-c5040680-8c92-11e9-9e4c-d3b935d57da8.png)

I clicked "no" because I didn't really know what the question was and it deleted the picture, which is what I wanted but not what I expected after saying no.

Now when I delete images I go straight to this dialog which is very useful. 

![Screen Shot 2019-06-11 at 9 53 02 pm](https://user-images.githubusercontent.com/29908924/59269978-ad794d80-8c93-11e9-82a7-b1f0298cb867.png)

I'm running MFractor 3.8.3 with preview features enabled in VS Mac 8.0.9.

What was that popup meant to do if I had said yes? Should I have been able to cancel out of it to not delete the image?

**Comment by matthewrdev** [comment]
The “would you like to use the deletion tool” is an MFractor workflow helper, however, it can definitely be improved. I’m pretty sure there is more text that should be displayed here to indicate it’s an MFractor action so will have to take a look into improving it.

Would some MFractor branding help here and/or more descriptive text?

**Comment by matthewrdev** [comment]
Yes, the pop up should show this tool when you say “yes”. It detects when you delete two images of the same asset (eg the @2x and @3x) and then triggers.

As the detection happens after the fact, Choosing no here won’t show the tool and doesn’t affect any deletion events.

**Comment by lachlanwgordon** [comment]
The cropped text and large blank button were what scared me in to clicking no, I'm having trouble recreating it now.

Should that popup happen every time or is it meant to be one time only?

**Comment by matthewrdev** [comment]
Oh geez, I just had another look at that image and it’s one mangled dialog there.

I think it’s a one time thing but I’ll check the code. Was the nudge useful? Should I make it repeat each time it detects this workflow?

**Comment by lachlanwgordon** [comment]
I'm still a little confused as to what it's meant to do because I've never seen it work properly.

Is that dialog meant to be a one time prompt to ask if you want to use the mFractor image deleting tool? If you say yes, from then on you will automatically get it every time you delete an image? If you say no you have to keep on deleting the different scalings manually like a pleb?

I'm happy to just always automatically go straight to the tool and wouldn't want to be asked every time.

**Comment by matthewrdev** [comment]
“Like a pleb” 😂😂

It does indeed only prompt you once and then never runs again. Maybe the better behaviour is as you suggested. Detect that you are deleting the density variants of an image asset and then auto launch the deletion tool? Would that suffice?

**Comment by lachlanwgordon** [comment]
Detecting sounds great. Would this be triggered regardless of whether I delete an image from the solution browser or the MFractor asset manager? That would be ideal.

**Comment by matthewrdev** [comment]
Definitely from the solution pad and I’ll check if it’s possible to delete a single image from the image manager. To my knowledge (need to jog my memory here), I think the image manager only ever lets you delete images using the deletion tool.

Let me check.

**Comment by matthewrdev** [comment]
Yep, you can only delete image assets in bulk in the image manager through the deletion tool. Might be worth considering exposing this for single densities as well 🤔

**Comment by matthewrdev** [comment]
Hey @lachlanwgordon, this has been fixed and will be in the next release for VS Mac 8.1. Will let you know when I’ve published it and close this issue.

Thanks for the great feedback as always!

**Comment by lachlanwgordon** [comment]
Sweet, thanks!

**Comment by matthewrdev** [comment]
Resolved in 3.8.6
