### ISSUE TITLE
The following extensions could not be started

### ISSUE THREAD

**Issue by delakti** [mfractor/mfractor-feedback#113]
Visual studio is complaining of **"The following extensions could not be started"** on opening.
![Screenshot 2019-06-17 at 08 34 44](https://user-images.githubusercontent.com/3205975/59586964-0c97f180-90dc-11e9-9730-4abdbf0d8c58.png)

It crashes the application during navigation or during use
Please advice

##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 18.6.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 3.8.4
Product Variant: Visual Studio For Mac
Product Variant Version: 8.1.0.2742
Product SKU: MFRACTOR-VS-MAC
Commit SHA: e9679c67c384490ad444ec9d483db757b3897b6c
Revision: 3403
Branch: master
Date: 3/06/2019 5:29:04 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by lachlanwgordon** [comment]
I had this issue but got around it.

I think what i did was:
1. Open extension manager
2. Remove Mfractor
3. Install MFractor - This will install the latest version 3.8.6 but you've got 3.8.4 which doesn't work with VS Mac 8.1

**Comment by matthewrdev** [comment]
Hi @delakti, could you try the steps that @lachlanwgordon has listed above and let me know if it works.

Also, please update to v3.8.8. You may find this resolves the issue.

**Comment by matthewrdev** [comment]
Hi @delkati, I’m closing this issue as I haven’t heard further information regarding this issue. If you’re still having problems, please reopen this ticket.
