### ISSUE TITLE
Search for usages does nothing

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#114]
When I click "Search for usages" in the context menu in the asset manager nothing happens.

This feature was working well in 3.8.4 although with warning about it being a preview feature.
Feature was removed in 3.8.5.
The menu option came back in 3.8.6 doesn't work.

Running VSMac 8.1(272)

**Comment by matthewrdev** [comment]
Fixed and available in 3.8.7.
