### ISSUE TITLE
Release notes request

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#115]
Hi,
Fairly low priority but I'd really like it if the release notes were more informative than "New version available". It makes it easier to discover new features.

Sorry to be a pain, I dread writing release notes for anything other than major feature releases so I understand if you don't want to or if it doesn't work with your workflow/release system.

![Screen Shot 2019-06-17 at 4 04 29 pm](https://user-images.githubusercontent.com/29908924/59587106-d7b18c00-9127-11e9-9009-c2845b8c4e6f.png)

**Comment by matthewrdev** [comment]
Completely agree here.

I've chased up the VS Mac team about how to do this in the past but didn't get much of a response so it never got acted on.

Will tee this up for investigation.

**Comment by matthewrdev** [comment]
Investigation notes... Could be driven by this:

https://github.com/mrward/monodevelop-nuget-addin/blob/08b2d57263f1b991253fe9001b97384d56d9d5f7/src/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml#L12

**Comment by matthewrdev** [comment]
@lachlanwgordon Would keeping an updated release note section on our docs site be suitable for this?

**Comment by matthewrdev** [comment]
@lachlanwgordon We have published a new docs.mfractor.com site and will now be keeping track of our release notes here: http://docs.mfractor.com/release-notes/mac/current/
