### ISSUE TITLE
Thoughts on Linker exclude workflow

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#116]
I love the "exclude from linking" quick fix. I think there are a couple of things to add to make it better. This could have been filed as separate issues but they probably make sense as an overhaul of the feature if addressed so I'm putting them together.

My first issue is that when you select "exclude from linking" the popup is itty bitty even though there's plenty of space.  This is fine in a classic forms app with only two projects that could be excluded but I have a solution with 4 so I have to resize every time.

<img width="406" alt="Screen Shot 2019-06-18 at 8 55 47 pm" src="https://user-images.githubusercontent.com/29908924/59677188-a3fc6200-920c-11e9-8308-4e5b49d7ef2e.png">

The next related issue is that I always want to exclude it in the same two libraries and not in the other two so it would be really nice if it remembered which projects I want to exclude. This would need to be recorded at a solution level. It wouldn't need any extra UI just a memory of the last selection.

Perhaps the lower down level issue to address is that two of these projects are libraries which are not directly exposed to the linker while two of them are apps that are. If you check the csprojs you can exclude projects with `<OutputType>Library</OutputType>` from this list and only offer it as a list for `<OutputType>Exe</OutputType>`.  I'm not 100% on this but I think my understanding of the linker is correct.

The other thing I'd like to see is a code preview.  The first time I used this feature I didn't know what it would generate or where. I thought it might have generated XML but also could have added a --linkskip. This would work well in a window similar to the mvvm wizard.

Perhaps a preference to --linkskip the assembly instead of just the member you were looking at would be another nice feature.

My final thought is that there was no way of knowing this was an mfractor feature rather than a VSMac feature.  When I found it I was so excited I wanted to thank whoever was responsible on twitter. I ended up disabling mfractor and restarting VS to find out.

If you want a solution that contains four projects as I mention above check out my visual nuget https://github.com/lachlanwgordon/Lachlan.Visual or any open source library that has separate projects for iOS/Android Nugets and a sample app in the one solution.

**Comment by matthewrdev** [comment]
![image](https://user-images.githubusercontent.com/3260473/59818299-a83c9280-9366-11e9-928a-115ae027d878.png)

Made a few adjustments to this. Bigger, saves preferences and includes branding.

**Comment by matthewrdev** [comment]
Available in v3.8.7
