### ISSUE TITLE
x:Name error

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#117]
Having several different styles with a VisualStateGroupList in app.xaml results in a error message that is not correct. See attached picture.
<img width="618" alt="Screenshot 2019-06-20 at 13 25 58" src="https://user-images.githubusercontent.com/13586354/59846126-517f8a80-935f-11e9-93ea-540f8d1cdf7f.png">

**Comment by matthewrdev** [comment]
Thanks for the report @MBrekhof. What is the code analysis issue that MFractor is reporting here?

**Comment by MBrekhof** [comment]
It tells me that the name is not unique (which is correct in this case)
<img width="403" alt="Screenshot 2019-06-24 at 07 53 35" src="https://user-images.githubusercontent.com/13586354/59994762-58efae00-9655-11e9-8ad9-219dad94a4c9.png">

**Comment by MBrekhof** [comment]
realized my comment might be confusing as to what exactly is the problem, a new screenshot just in case this helps:

<img width="743" alt="Screenshot 2019-06-26 at 09 21 07" src="https://user-images.githubusercontent.com/13586354/60159627-f1bc3000-97f3-11e9-87fd-cb43ec04e4aa.png">

**Comment by matthewrdev** [comment]
@MBrekhof This has been fixed and will be available in MFractor v3.9 (to be released in the next few days).
