### ISSUE TITLE
Enhancement: Ability to trigger i18n dialog from the MFractor menu

### ISSUE THREAD

**Issue by sthewissen** [mfractor/mfractor-feedback#118]
Is there a way to trigger the i18n dialog from the menu? Currently, it's only triggerable by right-clicking an untranslated text and hitting "Replace with RESX lookup" if I'm correct. However, I sometimes have files that are either half-translated or I just don't quite see whether or not everything is already translated due to the amount of XAML in the file. Being able to trigger the i18n using the menu would be nice to quickly ensure a file is completely translated without going through the entire XAML structure.

**Comment by matthewrdev** [comment]
Thanks for the suggestion @sthewissen, it's kind of a no-brainer!

I'm thinking this would be best placed in the top MFractor -> Wizards menu under an item named **Localisation Wizard**.

What are your thoughts on this?

**Comment by matthewrdev** [comment]
This is well underway @sthewissen and will be available in the next MFractor release as an item named **Localisation Wizard** in the top **MFractor** -> **Wizards**. This menu item will open the localisation wizard (if it's available) and focus the first localisable string in the document.

Thanks for the great feedback!

**Comment by sthewissen** [comment]
Hey Matthew, wow, that's fast! Awesome. I was even thinking: what are the options you could offer in the right-click menu for specific files? I'm not hindered with knowledge in that department 😅 You could even put something in there like "Localize file" but that might be overkill.

**Comment by matthewrdev** [comment]
Is this the menu you are thinking of?

![image](https://user-images.githubusercontent.com/3260473/59969126-01d0d700-958a-11e9-8e16-55009fea044c.png)

**Comment by sthewissen** [comment]
Ugh, obviously there are multiple menus... I just meant the solution explorer though :)

**Comment by matthewrdev** [comment]
Yeah that’s doable. The integration into this menu is already setup and the command I’m building hooks into it without much (if any) additional work.

So the answer is yes, but will take a little longer than the current work/changes.

**Comment by matthewrdev** [comment]
Well, this opened up a can of worms Steven. I'm currently swimming my way through tech-debt in our localisation feature suite 😂

Definitely a good thing, I owe you a beer/coffee next time we cross paths as a thank you!

**Comment by matthewrdev** [comment]
Mostly done:

![localise-wizard](https://user-images.githubusercontent.com/3260473/59972620-c956ea80-95d5-11e9-8469-4ee66ed880f8.gif)

There is some complexity getting this working in the right click context menu. For the moment this won't be supported.

This will released in MFractor 3.8.10.

**Comment by sthewissen** [comment]
Very cool! Getting paid in beer/coffee for giving other people more work to do sounds like I could make a day job out of that 🤔Just kidding obviously, awesome work!

**Comment by matthewrdev** [comment]
Interested in having a chat with me sometime Steven about localisation? I've got lots ideas I'd like to bounce off you and hear your thoughts.

Shoot me an email if you're interested: matthew@mfractor.com

**Comment by matthewrdev** [comment]
This has been added in MFractor 3.8.10, targeting Visual Studio Mac 8.1.1 (Build 27), and is now available.

**Comment by sthewissen** [comment]
Awesome!
