### ISSUE TITLE
Navigate to Binding stopped working

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#119]
Visual Studio 8.1.1 (build 27), MFractor 3.8.9 (Build 3511), somehow Command+D stopped working (old/new editor)

**Comment by matthewrdev** [comment]
Thanks for the report @MBrekhof. This is (again) likely caused by the VS Windows migration work. Let me take a look.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor 3.8.10.

**Comment by matthewrdev** [comment]
This has been fixed in MFractor 3.8.10, targeting Visual Studio Mac 8.1.1 (Build 27), and is now available.
