### ISSUE TITLE
Refactoring -> Replace with resx resource lookup doesn't function anymore

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#120]
mFractor 3.8.9, VS for Max 8.1.1 (build 27). In both the old and new c# editor the refactoring for string to resx values behaves strange: the string doesn't get replaced correctly unless you explicitly select it (next and/or replace have become useless).

**Comment by matthewrdev** [comment]
Hi @MBrekhof, I've just updated the ResX refactoring in v3.8.10 (released today).

Can you please update and re-test?

It's still failing, please zip up the log directory and attach to this ticket.

**Comment by MBrekhof** [comment]
ok, I'll let you know as you as I get the update

**Comment by matthewrdev** [comment]
HI @MBrekhof, I'm currently having issues where updates for MFractor aren't showing in the IDE. You can find the fix in this version of MFractor: https://addins.monodevelop.com/Stable/Mac/8.1.1/MFractor.VS.Mac.MFractor-3.8.11.mpack

**Comment by MBrekhof** [comment]
got it, thank you.

this issue is solved btw
