### ISSUE TITLE
Feature request: skip AutomationId when localising

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#122]
If easy/possible I would like the localisation routine to skip AutomationId's, see picture

<img width="705" alt="Screenshot 2019-06-26 at 19 45 08" src="https://user-images.githubusercontent.com/13586354/60202601-31facd00-984b-11e9-9d7b-5d92f01c9aab.png">

**Comment by matthewrdev** [comment]
Yes, I can make this happen.

Do you want this to be configurable (aka, users can choose to localise automationIDs) or to simply ignore it?

**Comment by matthewrdev** [comment]
Ok, and done.

![automation-id-fix](https://user-images.githubusercontent.com/3260473/60218145-cac43380-98b1-11e9-99d8-b8a669c2e284.gif)

**Comment by MBrekhof** [comment]
thanks
