### ISSUE TITLE
Problems initializing Mfractor in the las version of Visual Studio Xamarin 2019

### ISSUE THREAD

**Issue by FranCedron2690** [mfractor/mfractor-feedback#127]
Hi!

I recently downloaded the last MFractor version from the las update
 of Xamarin from Visual Studio Mac 2019. I have two problems, probably both relationed:

-After installed Mfractor, the window to activate license is not showed(I read the documentation and I supposed that it must be showed)

-Nothing is working correctly, and my Visual Studio is locked trying to load for example a new name command of a button. After closed Visual Studio, a new window appear and show me 2 error equals, that said "The following extensions could not be initialized". 

I send a capture (part of them is in Spanish, but the content of the error message is in English). I hope that can be resolved, because I think that is a wonderful tool for Xamarin.

Regards!!!

<img width="574" alt="Captura de pantalla 2019-07-26 a las 20 16 31" src="https://user-images.githubusercontent.com/9269823/61972617-4ebd2880-afe2-11e9-91a8-efdc3b62e2f5.png">

**Comment by matthewrdev** [comment]
Hi @FranCedron2690, it looks like you've fallen foul of an issue with our auto-updates.

Can you please follow these instructions to update and then confirm if it's addressed your issue: https://www.mfractor.com/blogs/news/mfractor-auto-updates-known-issue

**Comment by matthewrdev** [comment]
Hi @FranCedron2690, going to close this issue as haven't heard anything further and the above steps should address your problem.
