### ISSUE TITLE
Generate View Model Dialog needs more options

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#129]
It would be nice if the Generate View Model window had a few more options to bring it up to speed with the features in the MVVM wizard i.e. "ViewModel Base Class" and "Binding  Context Initialization".

Ideally these settings would have the default valudes fromt he "Project MVVM Settings" in the MVVM wizard.

e.g.
I have a content page with no BindingContext, I try to bind a command on a button and MFractor suggests generating a ViewModel
![Screen Shot 2019-07-31 at 4 22 44 pm](https://user-images.githubusercontent.com/29908924/62188365-767c0a00-b3af-11e9-8091-8d64f252a440.png)

The generate View Model page pops up and generates a ViewModel incliding the item you were trying to bind(which is awesome)
![Screen Shot 2019-07-31 at 4 23 22 pm](https://user-images.githubusercontent.com/29908924/62188650-5ac53380-b3b0-11e9-91e3-7d2ba997ad9f.png)

There's plenty of room on the left to choose a Base Class and Binding Context initialization which would match these settings.
![Screen Shot 2019-07-31 at 4 33 35 pm](https://user-images.githubusercontent.com/29908924/62188891-0a9aa100-b3b1-11e9-95ad-e882e4bc6397.png)

**Comment by matthewrdev** [comment]
@lachlanwgordon Thanks for the great feedback.

For some context, this particular window is a generic code generation window and doesn't fully tie into the MVVM generation engine. It was retro-fitted onto some very old functionality.

I agree that it needs to be expanded to include these additional options, after the IntelliSense migration is finished I'll take a look at this and how to expose out the MVVM wizard settings.

**Comment by matthewrdev** [comment]
## Technical Notes
As this feature leverages the generate code files infrastructure, we need to add a feature to that dialog that allows exposing of settings.  We can then leverage that new infrastructure to expose the  generate view model options/configuration into this dialog.

**Comment by matthewrdev** [comment]
@lachlanwgordon I have had feedback from other customers that this feature is confusing and have decided to remove it.

Additionally, the MVVM wizard serves the purpose for generating new view models and pages.

I am closing this issue.
