### ISSUE TITLE
Auto create of ViewModel don’t put the Bindingcontext in code behind

### ISSUE THREAD

**Issue by mfranc28** [mfractor/mfractor-feedback#130]
When using the auto creation of VieweModel the relative Bindingcontext in XAML code behind wasn’t create.

**Comment by matthewrdev** [comment]
Thanks for logging this issue Michelangelo.

Funnily enough @lachlanwgordon has filed a very similar issue at the exact same time. I'm going to close this as a duplicate of #129.

**Comment by lachlanwgordon** [comment]
wow, only one minute between the two.
