### ISSUE TITLE
VS for Mac 8.2.4 problem

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#133]
Hi
Basically I have the same problem as in #127, the only way to get VS working is to remove mfractor completely (I followed the steps you outlined in the webpage).

regards

**Comment by MBrekhof** [comment]
Update VS Mac to 8.2.5 (build 5), the download/install from inside VS still gives an error on startup. Installing 3.8.15 from file works.

**Comment by matthewrdev** [comment]
Thanks for reporting the issue @MBrekhof. We are aware of the installation issue (the extension repository is still publishing the wrong version) and are currently evaluating migrating away from the extension server.

In the meantime you can download the latest builds from here: http://addins.monodevelop.com/Project/Index/300
