### ISSUE TITLE
MVVM Wizard behaves very strangely if you use it in a brand new solution.

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#135]
I was using the MVVM Wizard in a brand new Forms Solution today and strange things were happening.
VSMac 8.2.15
MFractor 3.8.18
Full Install details here https://gist.github.com/lachlanwgordon/0bac280ef4f97298f6414b1abe0b7214 

Repro steps:
File>New Forms Shell App.
Run MVVM Wizard
Choose appropriate settings
All the things below happen.

Work Around:
Restart VSMac, everything works fine.

## Issue 1 The projects list displays a -xaml project that doesn't exist in my solution. This is for both the View Project and the ViewModel Project Settings
![Screen Shot 2019-09-05 at 8 10 31 pm](https://user-images.githubusercontent.com/29908924/64333428-d2265c80-d019-11e9-9260-cda22d9b2297.png)

## Issue 2
When I click the magic wand to locate a ViewModel, it says it can't find one, but I have two ViewModels that inherit from a BaseViewModel.
![Screen Shot 2019-09-05 at 8 11 18 pm](https://user-images.githubusercontent.com/29908924/64333643-54168580-d01a-11e9-97b0-ed8e5ee7472f.png)

## Issue 3
The .xaml page it generated does not have a backing .xaml.cs
![Screen Shot 2019-09-05 at 8 11 54 pm](https://user-images.githubusercontent.com/29908924/64333770-9f309880-d01a-11e9-806f-098c52339d63.png)

## Issue 4
The Xaml it does generate has a stray : in it for the Xamarin Forms namespace
![Screen Shot 2019-09-05 at 8 12 13 pm](https://user-images.githubusercontent.com/29908924/64333840-c5eecf00-d01a-11e9-8ea7-53b5ba82622c.png)

## Issue 5
The ViewModel isn't generated at all, it only shows my previous files.
![Screen Shot 2019-09-05 at 8 12 23 pm](https://user-images.githubusercontent.com/29908924/64333901-de5ee980-d01a-11e9-919b-ebff31e90c41.png)

## Issue 6
The Projects I choose are forgotten the next time I open the settings page. It defaults back to the non existent -xaml project.

Saved these settings
![Screen Shot 2019-09-05 at 8 19 32 pm](https://user-images.githubusercontent.com/29908924/64334053-2120c180-d01b-11e9-83b5-877c0623e591.png)

Reverts to these
![Screen Shot 2019-09-05 at 8 22 52 pm](https://user-images.githubusercontent.com/29908924/64334106-372e8200-d01b-11e9-86d5-180791a4ff1c.png)

## Issue 7 Prism Binding Context Initialization doesn't happen
My register types method in app.xaml.cs is as it was before.
![Screen Shot 2019-09-05 at 8 25 19 pm](https://user-images.githubusercontent.com/29908924/64334248-7d83e100-d01b-11e9-915e-47653a7a949f.png)

## Issue 8 Several MFractor options are missing from menu if you Create a Blank Forms App
![Screen Shot 2019-09-05 at 8 41 43 pm](https://user-images.githubusercontent.com/29908924/64335529-58dd3880-d01e-11e9-9157-34736649f234.png)

**Comment by matthewrdev** [comment]
@lachlanwgordon  Thanks for reporting these issues.

Several of these issues sound like a by-product of that `LocationTracker-Xaml` project. This project is a design-time project auto-created by VS Mac for XAML IntelliSense and has only just started to appear in VS Mac.

I'll investigate each of these issues and get back to you.

**Comment by matthewrdev** [comment]
@lachlanwgordon I believe the 3.8.23 update should have fixe these issues. Can you check and confirm? If fixed, will close this ticket.

**Comment by lachlanwgordon** [comment]
Works like a charm. Cheers.
