### ISSUE TITLE
Enhancement: Delete Output folders Extending and Configuring

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#136]
I love the delete output folders feature but there are two situations where it could be improved.

## 1. Delete .vs
When working on .Net Core Web projects in Visual Studio Windows it is quite common to have to delete the .vs folder to fix IIS port problems. It would be nice if delete output folders could delete this too. However this always requires a solution reload and more often than not, I only want to delete bin/obj but don't need to reload. 

## 2. Don't delete packages
Sometimes I need to delete bin and obj but I don't have network access or access to certain private nuget feeds, or I can access them but don't want to sit through a slow restore process unnecesarily. e.g. Switching from Debug to Release in a Blazor client side project requires a bin/obj delete but no restore.
e.g. Opening a solution in VS Windows that was built in VS Mac requires bin,obj to be deleted.

## UI
Cramming all that into the right click menu would get messy, even if you use a sub menu. I think the cleanest way would be:
When you Right-Click>Delete Output Folders, it shows a popup with checkboxes for which folders to delete. The default would be the current configuration of Bin,Obj and packages with an extra option for .vs. You can then have a checkbox near the "Okay" button to say "always do this for this solution"

After you've selected "Always do this" you would need someway to change your mind later. Maybe this could be through a "Delete Output Folders(Advanced)" option in the right-click menu.

**Comment by matthewrdev** [comment]
@lachlanwgordon Would you picture these settings also being available in the global MFractor preferences menu?

I'll mockup a design for a Delete Ouput Folders dialog and get your feedback 👍

**Comment by lachlanwgordon** [comment]
They could go in the settings as well, but i think the main place to be able to change is through right-clicking on project/solution so you don't have to dig into the settings if you just want to do a different thing as a one off.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been completed and will be available in the next release.

Please see: http://docs.mfractor.com/utilities/delete-output-folders/#configuring-delete-output-folders-mac-only
