### ISSUE TITLE
Image importing triggered by adding image in the solution only adds to the other project

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#137]
When you drag an image into the Resources directory in iOS, VSMac asks if you want to copy. MFractor then asks if you would like to use the importer. 

![Screen Shot 2019-09-06 at 2 24 47 pm](https://user-images.githubusercontent.com/29908924/64401168-0f8af880-d0b3-11e9-89f5-513ad1dcf29a.png)
 I click yes and it shows the Import Image Asset, with iOS and Android ticked I click "Import Image"
![Screen Shot 2019-09-06 at 3 08 52 pm](https://user-images.githubusercontent.com/29908924/64402426-43b4e800-d0b8-11e9-90f2-d4eabf53b4fc.png)

The image has been inported into all the correct drawable folders for Android but my ios project only has the original, unscaled image.
![Screen Shot 2019-09-06 at 3 09 47 pm](https://user-images.githubusercontent.com/29908924/64402479-7bbc2b00-d0b8-11e9-998a-903b019e311c.png)

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been fixed and will be included in our next service release (3.8.19).

After importing the image asset, MFractor will now ask if you'd like to delete the original project file.

**Comment by lachlanwgordon** [comment]
yay, thank you.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been released and is available in MFractor v3.8.19.

If you do not receive an update, please try installing using this link: http://addins.monodevelop.com/Stable/Mac/8.3.1/MFractor.VS.Mac.MFractor-3.8.19.mpack

**Comment by lachlanwgordon** [comment]
Awesome, thanks @matthewrdev, I'll test it out today. 

The VSMac update window is showing the update.
