### ISSUE TITLE
Suggestion: Change the Delete Output Folders location

### ISSUE THREAD

**Issue by kphillpotts** [mfractor/mfractor-feedback#139]
I find the current location of the `Delete Output Folders` and `Clean and Compress` to be too easy to accidentally click. 

![image](https://user-images.githubusercontent.com/1327346/64748467-9c233400-d555-11e9-8fd0-598d5ad0bb84.png)

Not sure how much control you have over the location in the context menu, but it would probably be better next to the existing `Clean Solution` menu option.  Also it could be in the Extensions -> MFractor menu

##Installation Information

```
--Platform Information--
Operating system is Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.18362.0
--MFractor Information--
Product Name: MFractor
Product Version: 0.1.8
Product Variant: Visual Studio For Windows
Product Variant Version: Microsoft Visual Studio
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 38540cb81138637d2bc84d2dc2f297984ab8f16d
Revision: 3260
Branch: master
Date: 15/05/2019 2:26:45 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
@kphillpotts This has been fixed in v0.1.3 of MFractor for Visual Studio Windows. I've provided you a link for an updated build via DM.
