### ISSUE TITLE
Import Image Dialog Feedback

### ISSUE THREAD

**Issue by kphillpotts** [mfractor/mfractor-feedback#140]
1. I think there might be some file locking going on.  If I select an image from this dialog, and then cancel (close the dialog), then go and try and re-export an image from adobe xd to overwrite the file it says the file is in use.

2. Looks like there might be some font sizing / DPI issues with the Import Image Dialog.

![image](https://user-images.githubusercontent.com/1327346/64749749-0d64e600-d55a-11e9-85ba-579095a19eee.png)

Interestingly the screen this is on, is a normal 100% DPI but not

3. When importing image it doesn't appear to be setting the correct build actions for Android (just leaves it as none)

##Installation Information

```
--Platform Information--
Operating system is Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.18362.0
--MFractor Information--
Product Name: MFractor
Product Version: 0.1.8
Product Variant: Visual Studio For Windows
Product Variant Version: Microsoft Visual Studio
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 38540cb81138637d2bc84d2dc2f297984ab8f16d
Revision: 3260
Branch: master
Date: 15/05/2019 2:26:45 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
@kphillpotts I've fixed the build action issue in the image importer for Android assets. Next release will set the BuildAction to "AndroidResource".

Looking into the other issues.

**Comment by matthewrdev** [comment]
Closing as this dialog was rebuilt in WPF and should address these issues.
