### ISSUE TITLE
When I start VS for Mac, System.Reflection.TargetInvocationException occurs.

### ISSUE THREAD

**Issue by WarriorBlue** [mfractor/mfractor-feedback#141]
This is an exception, and it says that:
Error: Error while getting object for node in path ‘/MonoDevelop/ide/DisplayBindings’
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 18.7.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 3.8.4
Product Variant: Visual Studio For Mac
Product Variant Version: 8.2.6.26
Product SKU: MFRACTOR-VS-MAC
Commit SHA: e9679c67c384490ad444ec9d483db757b3897b6c
Revision: 3403
Branch: master
Date: 3/06/2019 5:29:04 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
@WarriorBlue Can you please uninstall any existing installations of MFractor and install the latest version from there: http://addins.monodevelop.com/Project/Index/300
