### ISSUE TITLE
A pointer is located incorrectly after IntelliSense completion

### ISSUE THREAD

**Issue by rotorgames** [mfractor/mfractor-feedback#142]
I found that after finishing auto-completion a pointer is located at the end of the line but not in " ". It happens with Setters in Style for example. Please, take a look.
![Oct-04-2019 09-39-37](https://user-images.githubusercontent.com/1790504/66183741-f2821f00-e68a-11e9-8913-c3e5f7d22f29.gif)

**Comment by matthewrdev** [comment]
@rotorgames This has been fixed and will be available in MFractor v3.9 which will be released in the coming few days.

**Comment by matthewrdev** [comment]
![Uploading image.png…]()

**Comment by matthewrdev** [comment]
![insertion-bug](https://user-images.githubusercontent.com/3260473/66262515-53455f00-e825-11e9-8985-52e911d76d81.gif)
