### ISSUE TITLE
Mfractor Says Title and Subtitle are invalid FontSizes but it works and is in official doc

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#143]
Here's the Mfractor Error
<img width="684" alt="Screen Shot 2019-10-16 at 3 11 11 pm" src="https://user-images.githubusercontent.com/29908924/66887648-5a3f4f00-f027-11e9-9634-c277ca8a5075.png">

and here's the allowed sizes from https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts
<img width="897" alt="Screen Shot 2019-10-16 at 3 12 51 pm" src="https://user-images.githubusercontent.com/29908924/66887676-73480000-f027-11e9-8f28-7439f8d4ce81.png">

**Comment by matthewrdev** [comment]
@lachlanwgordon  This has been fixed and will be available in MFractor v3.8.23.
