### ISSUE TITLE
MFractors XAML code actions are not accessible through the "Option+Return" menu

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#145]
As per description. More detail to be added if needed.

**Comment by matthewrdev** [comment]
A call with Visual Studio Mac is scheduled for 11th of December to discuss this issue.

**Comment by matthewrdev** [comment]
Currently in discussions with the VS team on addressing this (the API we use to provide actions on Windows should work on Mac).

As a work-around, we now suggest available fixes in our code issues tooltips.

**Comment by matthewrdev** [comment]
This is now fixed and will be available in MFractor 4.1.2. 🥳

**Comment by ravero** [comment]
At least!! 👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻 
Thanks!
