### ISSUE TITLE
Image import tool bug iOS

### ISSUE THREAD

**Issue by WouterStraver** [mfractor/mfractor-feedback#147]
On the latest version (3.8.25) the images on iOS are imported differently. And because of that they aren't working. 

Before the were imported like: 
`<ImageAsset Include="Assets.xcassets\arrowline.imageset\arrow_line.png" />`

And now like 
`<None Include="Assets.xcassets\ic_trainingen_tab.imageset\arrow_line.png" />`

Or did I configured something wrong?
For Android it's working fine.

**Comment by matthewrdev** [comment]
@WouterStraver This is just flat out a bug. Let me look into it.

**Comment by matthewrdev** [comment]
@WouterStraver What version of Visual Studio Mac are you using?

**Comment by matthewrdev** [comment]
@WouterStraver This has been fixed and will be available in MFractor v3.9
