### ISSUE TITLE
Introduce XLIFF Support for Localization

### ISSUE THREAD

**Issue by dansiegel** [mfractor/mfractor-feedback#15]
# Description

Currently the Localization support provides an ability to import/export an excel spreadsheet. The issue is that this is ultimately opinionated and error prone as I could send off an excel spreadsheet to someone who could make some crazy change in excel that wouldn't work well for importing changes. A better and more cross platform friendly implementation would be to adopt the XLIFF 2.0 format and essentially match what the Multilingual App Toolkit provides in VS 2017. Since XLIFF is already a standard it would make it far easier for exporting/importing cross platform.

- [XLIFF](https://en.wikipedia.org/wiki/XLIFF)
- [Translating Mobile Apps With The Multilingual App Toolkit with Cameron Lerum](https://channel9.msdn.com/Shows/XamarinShow/Translating-Mobile-Apps-With-The-Multilingual-App-Toolkit-with-Cameron-Lerum)
- [simonech/XliffLib](https://github.com/simonech/XliffLib)
- [fmuecke/XliffParser](https://github.com/fmuecke/XliffParser)

**Comment by matthewrdev** [comment]
Hi Dan, completely agree. Ideally, we'd like to able to import and export from a variety of sources, XLIFF being our preferred approach.

I don't have a timeframe on supporting this but yes, we do plan on doing this.

**Comment by matthewrdev** [comment]
Closing this as it’s a very old ticket and we’ll create specific tickets when we start work on this feature suite. After MFractor Windows, I’ll start investigating how MFractor can improve localisation tooling for Xamarin developers.
