### ISSUE TITLE
Error message when saving preferences -> code analysis

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#150]
(not sure whether or not this is a MFractor problem) When changing and saving code analysis preferences VS tells me that there was an error saving the changes when changing this setting. Re-loading the project shows  the changes were saved
<img width="963" alt="Screenshot 2019-11-29 at 15 23 10" src="https://user-images.githubusercontent.com/13586354/69919941-9832ee00-1482-11ea-9d2f-943c41f2342b.png">
.

**Comment by matthewrdev** [comment]
Thanks for reporting the issue @MBrekhof. Could you also please attach or email your IDE.log files? Please see http://docs.mfractor.com/support/#visual-studio-mac

**Comment by MBrekhof** [comment]
ok
[Archive.zip](https://github.com/mfractor/mfractor-feedback/files/3908722/Archive.zip)

**Comment by MBrekhof** [comment]
solved in 3.9

**Comment by matthewrdev** [comment]
@MBrekhof Good to hear! 👍
