### ISSUE TITLE
Custom Keyboard Bindings for MFractor Functions

### ISSUE THREAD

**Issue by rajczi** [mfractor/mfractor-feedback#151]
I'd love to have all the MFractor commands available in the Key Bindings area so custom keyboard shortcuts could be mapped directly to your functions.

On VS Mac: Visual Studio Menu -> Preferences -> Environment -> Key Bindings

If possible, I'd expect MFractor to have a section heading in that dialog with all of its main commands listed where we could enter a customer keyboard shortcut.

**Comment by matthewrdev** [comment]
Thanks for the feedback @rajczi 🙏

**Comment by matthewrdev** [comment]
This has been completed and will be available in MFractor v3.10.3

![image](https://user-images.githubusercontent.com/3260473/73516717-0c6b1d00-4445-11ea-8cd7-33306802a1e3.png)

**Comment by ravero** [comment]
Next step is to think about some of the most commonly used commands and think about some defaults, what you think @matthewrdev ? Maybe we can check our telemetry to figure it out.
