### ISSUE TITLE
Value Converter Wizard Enhancement

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#154]
When you use the Value Converter wizard, it would be cool if as well as generating the Converter, it also added the converter as a Static Resource in your xaml and added the xmlns for converters if not already present in the xaml.

For the UI in the wizard this would be an extra field on the left to specify which .xaml file to add it to. You'd want the option to choose App.xaml if you think it's a converter you'll use everywhere in your app or a specific xaml which would ideally default to the currently open xaml file if available.

As icing on the cake you could have the wizard be triggerable by a quick fix that is available when the cursor is on any binding in xaml. This would also set the converter on the property in xaml along with generating the generator and the static resource.

**Comment by matthewrdev** [comment]
I like this suggestion!

MFractor already has all of the infrastructure to do this (thanks to the extract style refactoring) so I'll get it done.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been added and will be available in 3.9.1.

**Comment by lachlanwgordon** [comment]
This feature inserts the snippet in the middle of the first existing StaticResource.

e.g. I try to make a new converter called DoubleToBool with `Create XAML Entry` and my current page selected.
![Screen Shot 2019-12-06 at 7 27 55 pm](https://user-images.githubusercontent.com/29908924/70308051-91c7bc00-185e-11ea-85b7-553f1df28a9a.png)

The Static Resource it generates is right in the middle of the word Target for one of my existing styles.

![Screen Shot 2019-12-06 at 7 28 59 pm](https://user-images.githubusercontent.com/29908924/70308150-c3d91e00-185e-11ea-9ba5-4ee115b9c3ff.png)
