### ISSUE TITLE
Generating a value converter from the context menu in a xaml file sets the wrong namespace if the output type is a primative

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#157]
Ready for a weird one?

In my Xaml I declare that the value converter for a binding is something that doesn't exist yet. When ask Mfractor to generate it, it mostly works but the name space is set to the output type. This seems to only happen if the output is a primative but not with reference types. This occurs if the output type is int, double, string(not actually a primative but darn close). This does not occur with classes, tested with the Xamarin Forms Type TextAllignment.
double is a keyword so it not a valid namespace so there's a compiler warning to alert you of the issue farely quickly.

e.g.
I try to generate a StringToDouble converter
![Screen Shot 2019-12-05 at 5 06 28 pm](https://user-images.githubusercontent.com/29908924/70208927-ec8be580-1782-11ea-8b46-b1a7e87b6f47.png)

And the generated converter has the name space double
```
namespace double
{
    [ValueConversion(typeof(object), typeof(object))]
    public class StringToDoubleConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is object == false)
            {
                return default(object);
            }

            var input = (object)value;

            // TODO: Put your value conversion logic here.

            return default(object);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been fixed and will be released in MFractor 3.9.1.
