### ISSUE TITLE
Value converters generated from Xaml Context menu are created in a folder with the name of the input type

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#158]
When you generate a converter from xaml, it puts it in a folder based on the input type.

I would have expected it to be created in  the Converters folder, which is where I like to keep them and where the Wizard puts them.

Seems like this issue and the others I've just reported are around a list of arguments and your indexes are off by one, or maybe 2.

Here's my hot mess of a project structure including a . in a folder name.
![Screen Shot 2019-12-05 at 5 25 59 pm](https://user-images.githubusercontent.com/29908924/70209454-67a1cb80-1784-11ea-8aa4-53f3fd7dac57.png)

**Comment by matthewrdev** [comment]
Well this is a hot mess. Looking into it.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been fixed and will be released in MFractor 3.9.1.
