### ISSUE TITLE
Docs Pencil button leads to 404

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#159]
Every page in the Docs has a pencil button sugesting users can edit. When you click it you get a 404.

Not sure whether you want it to lead to a page so users can contribute, or if the button should be hidden completly, but probably one of these.

**Comment by matthewrdev** [comment]
@lachlanwgordon This is now fixed and live on our documentation site. The "Pencil" now links out to the correct documentation page and branch for editing.

Can I please confirm that it's fixed before closing this ticket?

**Comment by lachlanwgordon** [comment]
This works, it takes you to the relevant file on github
