### ISSUE TITLE
IntelliSense on VS4Mac XAML Editor Not Showing Any Entries

### ISSUE THREAD

**Issue by Osmosis311** [mfractor/mfractor-feedback#16]
![image](https://user-images.githubusercontent.com/360240/40950665-b3554852-6841-11e8-852d-72a6fcaee6bb.png)

**Comment by orestesgaolin** [comment]
Had the same problem on VS4Mac Beta (Preview)
Downgraded to stable channel and unfortunately had to reinstall VS4Mac. 
Now everything works properly.

**Comment by matthewrdev** [comment]
Hi @Osmosis311, @orestesgaolin

Is this still affecting you in Visual Studio Mac 7.6.6 and MFractor 3.5.21? Please try in these versions and let me know. We worked to fix a lot of XAML IntelliSense bugs in our latest releases, they **should** address this issue.

**Comment by matthewrdev** [comment]
Hi Danny, based on our conversations via email I'm going to mark this issue as fixed.

Please re-open or file a new bug if this happens again.
