### ISSUE TITLE
Docs pages that are not listed are searchable

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#160]
If you search the Docs for Value Converter, it will take you to a stub page that is just a title. I guess the page exists as a marker for where you will write docs in the future but if you can hide these useless pages from the search that would be good.

**Comment by matthewrdev** [comment]
@lachlanwgordon I'm aware of this, however, just bear with us for a month or so while we get all of these docs built.

**Comment by matthewrdev** [comment]
Thanks for the feedback, however, closing as this is expected while we are rebuilding the docs site.
