### ISSUE TITLE
Value Converter Wizard and Actions have no docs

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#161]
There are no docs about Value Converter Wizard or the context action generations for them.

I went looking because I didn't know what a Value Converter Parameter was after seeing it in the wizard. Turns out that was a gap in my knowledge and the answer lay in the Xamarin Forms docs.

Thanks for teaching me, I needed that feature from forms and I may have implemented something wacky myself if I hadn't found it.

I know you've just redone the docs so there are gaps, no rush on this but I thought I'd let you know. New Docs site looks great by the way.

**Comment by matthewrdev** [comment]
@ravero Could you please build out the documentation for the value converter wizard?

**Comment by ravero** [comment]
Sure, I'm producing the docs. Will notify here when they're available.

**Comment by ravero** [comment]
Hi @lachlanwgordon, just a follow up to let you know that the MFractor Value Converter Wizard docs are available at: https://docs.mfractor.com/xamarin-forms/value-converters/value-converter-wizard/

If there are any doubts left about this feature please let us know, so we can enhance the documentation!

Regards.
