### ISSUE TITLE
Binding validation error for static source references

### ISSUE THREAD

**Issue by rajczi** [mfractor/mfractor-feedback#163]
When entering a binding with the following syntax:

`TextColor="{Binding BackgroundColor, Source={x:Static local:App.Settings}}"`

the validator incorrectly marks this as invalid saying

`The path 'BackgroundColor' does not resolve to a property in the binding context 'MainViewModel'`

MainViewModel is the correct binding context for the overall view but not this particular binding.

**Comment by matthewrdev** [comment]
@rajczi This has been fixed and will be released in MFractor 3.9.5.

**Comment by matthewrdev** [comment]
![image](https://user-images.githubusercontent.com/3260473/71386795-5d1c7880-2644-11ea-9466-843ad176b00e.png)
