### ISSUE TITLE
Binding validation not run with dotted notation bindings

### ISSUE THREAD

**Issue by rajczi** [mfractor/mfractor-feedback#164]
In a valid binding with the following format:

`TextColor="{Binding Settings.BackgroundColor}"`

MFractor does not validate the binding syntax.  Changing the binding to

`TextColor="{Binding WrongSettings.BackgroundColor}"`

or

`TextColor="{Binding Settings.WrongBackgroundColor}"`

will not yield an indication of an invalid binding syntax.

**Comment by matthewrdev** [comment]
@rajczi I've been looking into how MFractor handles binding validation and there is explicit excludes on `.` notation. Just a heads up, this will take a bit of work to fix therefore a fix before the end of this year is unlikely.

Just keeping you in the loop.
