### ISSUE TITLE
Feature request - Delete (or show) unused nuget packages.

### ISSUE THREAD

**Issue by WouterStraver** [mfractor/mfractor-feedback#167]
Based on the feature request for unused images I was thinking it would be nice to have the same functionality for nuget packages. This would improve the maintainability of an app a lot. 

Would like to know what you think about this.

**Comment by matthewrdev** [comment]
@WouterStraver I really like this idea and it continues nicely with the theme set by the unused image assets feature request. I'm slowly formulating what an app-wide solution analyser would look like and this also fits in well with that theme.

Lastly, just to be clear, this is on the more complex end of the spectrum for feature requests. We are unlikely to implement this in the immediate future and rather more in the 6+ month timeframe.

**Comment by WouterStraver** [comment]
I understand this will not be top priority, but glad to hear you like the idea. It will be worth to wait for 6+ months ;-)

**Comment by matthewrdev** [comment]
Going forward, MFractor will be focusing exclusively on the MAUI feature set. Closing.
