### ISSUE TITLE
Delete Output Folders Preferences Behave strangely if you have a solution and a project with the same name

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#168]
When I try to adjust the delete output folders preferences for a solution the checkboxes toggle different boxes to where you tick. I think it's related to having two items with the same name, it doesn't seem to affect other items.

![delete](https://user-images.githubusercontent.com/29908924/70569748-a2758a80-1bee-11ea-9c8b-887fee7a2abf.gif)

**Comment by matthewrdev** [comment]
Wow, that's not nice!

Thanks for reporting @lachlanwgordon, I'll look into it and aim to get a build out for you today.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been fixed and is available in MFracto v3.9.3
