### ISSUE TITLE
Add ability to remove imported images from projects

### ISSUE THREAD

**Issue by orestesgaolin** [mfractor/mfractor-feedback#17]
I'd like to be able to remove imported images by e.g. selecting image from the list in _Image Wizard_ as well as the projects to be removed from.

**Comment by matthewrdev** [comment]
This is a fantastic suggestion; I had this exact thought the other day. We'll looking into getting this into our 3.7 release (we'll be focusing on image tools in 3.7).

**Comment by matthewrdev** [comment]
This feature is confirmed for MFractor v3.7.

**Comment by matthewrdev** [comment]
@orestesgaolin This feature is now available in MFractor v3.6.2
