### ISSUE TITLE
Weird issue with MFractor dialog not being dismissed

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#170]
There is a weird issue with the MFractor dialog still being displayed after it is dismissed, and when clicking on Check for Updates within VS 2019 8.3.10 (Build 2) for Mac.

I have attached a screen cast video in the attached zip file.
[MFractor-Dialog-Issue.zip](https://github.com/mfractor/mfractor-feedback/files/3948833/MFractor-Dialog-Issue.zip)

**Comment by matthewrdev** [comment]
@geniesoftstudios Can you please reproduce this issue and then send me the last 5 log files for that IDE session?

The IDE log files can be found under **Help** -> **Open Log Directory**.

**Comment by geniesoftstudios** [comment]
@matthewrdev just sent you an email with the log files.
