### ISSUE TITLE
MFractor VS for Mac Licensing Dialog Issue

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#176]
There seems to be an issue with the MFractor Licensing dialog when choosing your licence file, and clicking on the Select File button. Licensing details are added to MFractor, and a dialog of Ok is displayed. 

Upon clicking on OK button within the "Your MFractor license has been succesfully loaded Ok", the underlying Select File dialog doesn't dismiss when you click Cancel. The only way to fix this issue, is to Quit or Force Quit Visual Studio for Mac.

Screenshots Attached.
![MFractor1](https://user-images.githubusercontent.com/2282817/71223924-3c44e200-2329-11ea-9274-5a45e763d062.png)
![MFractor2](https://user-images.githubusercontent.com/2282817/71223926-3c44e200-2329-11ea-9a1a-266521223972.png)

**Comment by matthewrdev** [comment]
Related to #170

**Comment by matthewrdev** [comment]
@geniesoftstudios Can you please download v3.9.6 for Visual Studio Mac 8.4 and check if this issue still persists? We have change some of our dialog handling and it *may* correct this bug.

**Comment by geniesoftstudios** [comment]
@matthewrdev I have downloaded and tested MFractor v3.9.7 for Visual Studio for Mac 8.4 and the issues experienced are no longer present. Everything is working as expected. :-)
