### ISSUE TITLE
Allow files to be included/excluded on the image deletion tool

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#177]
The image deletion tool presents a list of images it's about to delete. It would be interesting to add to this list a checkbox field that would allow selecting individual files to include or exclude from the delete operation. Sometimes you may want to delete some but not all the files that compose the image set of an asset.

**Comment by matthewrdev** [comment]
This has been implemented and will be available in MFractor 4.2.10.

<img width="812" alt="Screen Shot 2020-07-13 at 8 38 32 am" src="https://user-images.githubusercontent.com/3260473/87258092-41939500-c4e4-11ea-9e06-a8e38e085a9f.png">
