### ISSUE TITLE
MVVM Wizard - Add Intellisense/Autocomplete to the base class fields

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#178]
The Settings page of the MVVM Wizard allows setting the base class for either the View and View Model parts of the MVVM Component. This is done through a regular Text Fields that allows typing the FQN of the Type to serve as the base for those parts.

It would be great to add some sort of Intellisense or Autocomplete to those fields, to facilitate finding the wanted type name.

**Comment by matthewrdev** [comment]
@ravero I've been investigating this.

While the XWT APIs allow us to set completions, the backing implementing in [Xamarin.Mac](https://github.com/mono/xwt/blob/ec734b3fc81994753e23d8b06c6d1878fe8f7b75/Xwt.XamMac/Xwt.Mac/TextEntryBackend.cs) and [WPF](https://github.com/mono/xwt/blob/af2540cb0b6a1c1e82c4f7ec8949565f6677e631/Xwt.WPF/Xwt.WPFBackend/TextEntryBackend.cs) are not implementing. 

Unfortunately this is not possible at the moment.
