### ISSUE TITLE
MVVM Wizard - Color Coding the XAML File Previewer

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#179]
When Previewing XAML files on the MVVM Wizard (other dialogs that offer previewing XAML also), the code is not coloured being plain black/white. This makes harder to read the file.

The Previewer would implement color coding for XAML just like for C# files.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in the next service release (4.0.5)

**Comment by matthewrdev** [comment]
![image](https://user-images.githubusercontent.com/3260473/77020337-1df58d80-69cf-11ea-82dc-a0fbe5a1508b.png)
