### ISSUE TITLE
Weekly tips don't work with dark mode

### ISSUE THREAD

**Issue by jimbobbennett** [mfractor/mfractor-feedback#18]
As the title really, the weekly tips dialog box is unreadable with dark mode, and the tips themselves look weird as light on a dark dialog.

Also - how do you turn them off?

**Comment by jfversluis** [comment]
It can be turned off in **Visual Studio** > Preferences > MFractor > uncheck "Show product tips", only available with a professional license.

**Comment by matthewrdev** [comment]
@jimbobbennett To help me out (in triage and bug fixing mode today), can you include a screenshot of dark mode?

**Comment by matthewrdev** [comment]
Fixed, shipping in 3.6.

**Comment by matthewrdev** [comment]
<img width="1112" alt="screen shot 2018-09-30 at 9 07 53 am" src="https://user-images.githubusercontent.com/3260473/46251222-61cd9d80-c490-11e8-9231-71a826baf6dd.png">
