### ISSUE TITLE
Add search results to the Find Custom Renderers Code Action

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#183]
Instead of opening the first custom renderer found for a component, MFractor should display a dialog with the Code Actions found for that component and allow user to select the one he wishes to open.

This also allows the user to know all the Renderers that exists for that component.

**Comment by ravero** [comment]
Check `NavigateToFileSpansResponse` and `NavigateToFileSpansResponseHandler`.

**Comment by matthewrdev** [comment]
**Technical notes**
Add an additional boolean property *AutoOpenSingleResults* (or similar) to the response that defaults to `true` (to preserve existing behaviour) and implement this in the `NavigateToFileSpansResponseHandler`.
