### ISSUE TITLE
Small bug in color Intellisense warnings

### ISSUE THREAD

**Issue by sthewissen** [mfractor/mfractor-feedback#184]
When using the color #ffffff > White MFractor incorrectly suggests replacing it with Transparent.

![image](https://user-images.githubusercontent.com/2419439/72897573-910dbb00-3d22-11ea-88eb-7feeeda07534.png)

Probably a matter of not checking for alpha if it's not there.

**Comment by matthewrdev** [comment]
Thanks for reporting Steven, I’ll take a look and hopefully get a patch release out ASAP.

I can imagine this is a little distracting...

**Comment by sthewissen** [comment]
It really isn’t that big, just a small booboo I happened to notice and thought you’d want to know 😅 Can imagine there are more pressing matters!

**Comment by matthewrdev** [comment]
True... me vs bugs at the moment:

https://media3.giphy.com/media/e37RbTLYjfc1q/giphy.gif?cid=790b761106bca340e8bd58d69b5540c2ea6d0470366c13e9&rid=giphy.gif

**Comment by sthewissen** [comment]
Haha and here I come along with a punch to the nut sack after you’ve just fended off the world 😂 woops!

**Comment by matthewrdev** [comment]
This will be fixed in next release (3.10.1).

In this case, the warning will now become:

![image](https://user-images.githubusercontent.com/3260473/72938120-17bfa800-3db6-11ea-8891-809422a77f74.png)

**Comment by sthewissen** [comment]
Awesome! If you're coming to MVP Summit I'll bring you some stickers for your trouble ☺️
