### ISSUE TITLE
Grid Location Intellisense has unpredictable behaviour

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#185]
The Intellisense for the Grid that suggest `Grid.Row/Column` and `Grid.RowSpan/ColumnSpan` is presenting unpredictable behaviour. Sometimes it show only those suggestions, sometimes it shows only the native suggestions and doesn't show the grid ones.

The image below exemplifies the issue:
![2020-01-31 13 50 04](https://user-images.githubusercontent.com/1834963/73557823-af656c00-4430-11ea-9d91-8547d88a032f.gif)

**Comment by ravero** [comment]
I suspect that the results are not being merged to the native IntelliSense results.

**Comment by matthewrdev** [comment]
@ravero After much testing, unfortunately this is a Visual Studio issue. The built-in XAML completion provider is sometimes failing to provide symbols and that is why it sometimes doesn't display/
