### ISSUE TITLE
Solution/Project level Code Formatting

### ISSUE THREAD

**Issue by dansiegel** [mfractor/mfractor-feedback#19]
Intellisense generally gives us the ability to sort or sort & remove usings, and the IDE gives us the ability to format on save. It would be fantastic though if MFractor could add the ability at the Project and Solution Level to:

1. Sort usings in our C# classes
1. Sort and Remove unused usings in our C# classes
1. Fix the code formatting i.e. mixture of tabs/spaces, curly braces improperly applied (Stroustrup vs Allman)

**Comment by matthewrdev** [comment]
It looks like VS Mac has a service capable of doing this per document however not per-project or per-solution. Including this for future reference: https://github.com/mono/monodevelop/blob/305bddc1e9dcd90caf25f8bed1a042efc317528b/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/CodeFormattingCommands.cs

**Comment by matthewrdev** [comment]
Hi Dan, doing an issue cleanup here.

Going to close this as our current focus is on MFractor Windows. I’ll take a look at this after we have shipped windows and have capacity for new feature suites.
