### ISSUE TITLE
Add Image Tooling support for iOS projects

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#190]
The image tooling like the _Image Assets Intellinsense_ and the _Image Tooltip_ should be applied to Xamarin.iOS projects for it's SDK. The main class to look for is `UIImage` from UIKit and we should like when assign to properties of that type, or methods that receive arguments of this type.

**Comment by matthewrdev** [comment]
Image asset tooltips are now working for iOS projects. As IntelliSense/Code completion will require a significant amount of additional work, I'll close this ticket and reopen another specifically for intellisense when we get to it.

<img width="524" alt="Screen Shot 2020-07-08 at 11 45 20 am" src="https://user-images.githubusercontent.com/3260473/86864525-a92a9880-c110-11ea-8b87-c90d958c2fa5.png">
