### ISSUE TITLE
Hint window in dark mode for VS Win has low contrast

### ISSUE THREAD

**Issue by anotherlab** [mfractor/mfractor-feedback#193]
The colors used for the hint windows are hard to read when running VS windows in dark mode.

The message text color (#000000) is too dark against the hint window background (#666669).   That works out to a contrast ratio of 3.6:1.  You want to have a ratio of 4.5:1 or better for [WCAG AA compliance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum).  A text color of #F5F500 would give you a 4.88:1 ratio and would be easier to read.

The link text color (#0066CC) should be a lighter shade of blue.  It has a contrast ratio of 1:1.  Changing it to #D6EBFF would bring the contrast ratio to 4.68:1

![mfractor dark mode](https://user-images.githubusercontent.com/1191188/76098612-c818f280-5f97-11ea-8dce-d46312f02bd3.png)

**Comment by matthewrdev** [comment]
Thanks @anotherlab for flagging this. MFractor is using XWT to share UIs and it doesn't look like it is honoring the dark theme settings. Will look into it.

**Comment by matthewrdev** [comment]
@anotherlab MFractor will now honor the theme colors in tooltips. This is fixed and will be available in the next release 4.0.3.
