### ISSUE TITLE
No MFractor quick fix screwdriver when ReSharper extension enabled

### ISSUE THREAD

**Issue by Adam--** [mfractor/mfractor-feedback#196]
MFractor 4.0.5 (VS Windows)
ReSharper Ultimate 2019.2.2
Microsoft Visual Studio Professional 2019 16.4.1

With ReSharper enabled:
![image](https://user-images.githubusercontent.com/2179171/77071273-1f6c8900-69c2-11ea-9fd1-c3026b04b0a1.png)

With ReSharper disabled:
![image](https://user-images.githubusercontent.com/2179171/77071710-e385f380-69c2-11ea-91a1-322b78ba891f.png)

I was unable to find any other issues mentioning this nor anything on the documentation site with work arounds. It would be nice to be able to use both tools.

**Comment by matthewrdev** [comment]
@Adam-- Thank you for reporting this issue.

![image](https://user-images.githubusercontent.com/3260473/77115416-00313280-6a7a-11ea-8fec-cae12c17d7c2.png)

To ensure ReSharper merges in our code actions, go to the top Extensions menu, then ReSharper -> Options. In the options window, go to Editor -> Visual Studio Features and then check Merge Visual Studio light bulb actions into ReSharper action indicator.

This will enable all Roslyn code actions to be available through ReSharpers actions menus.

**Comment by Adam--** [comment]
Good call updating the documentation.

I'm not sure what version of ReSharper that screenshot is from, but on ReSharper Ultimate 2019.2.2 it is
**Code Inspection -> Settings -> Merge Visual Studio light bulb actions into ReSharper action indicator**
![image](https://user-images.githubusercontent.com/2179171/77164949-b5b6b280-6a87-11ea-8526-6cc5783cdc44.png)

Doing that then resyncing MFractor solution resources merged the two.

Thanks for the help.

**Comment by matthewrdev** [comment]
Glad to hear this is resolved @Adam--. May I close this issue?

**Comment by Adam--** [comment]
Sure, but I'd personally use this to track adding to the docs, unless you are tracking it elsewhere, your call of course.

**Comment by matthewrdev** [comment]
@Adam-- I have updated our docs to include this information. Please see https://docs.mfractor.com/resharper-compatibility/

Thanks for your help and patience, I'm now closing this issue.
