### ISSUE TITLE
Support for Build Time Generated Images

### ISSUE THREAD

**Issue by dansiegel** [mfractor/mfractor-feedback#198]
# Description

In an effort to reduce the complexity of handling in project image resources there are essentially 3 competing methods of dealing with this. One of course being the existing built in tooling from MFractor.

Both @redth and I have packages that can help you generate those images at build. Currently MFractor is not able to detect those images and shows an error for the missing image. 

## Proposal

MFractor should scan the intermediate outputs for images that have been generated. For instance the Mobile.BuildTools will generate the outputs where ever you would have expected them in the project but within the intermediate output directory. `{projectDir}/Resources/drawable/image.png` -> `{projectDir}/obj/Resources/drawable/image.png`

**Comment by matthewrdev** [comment]
This is now available in MFractor v4.0.12. See https://docs.mfractor.com/release-notes/mac/v4/v4.0/#v4.0.12
