### ISSUE TITLE
Generate a method named "MethodName" in code behind class not working

### ISSUE THREAD

**Issue by yurkinh** [mfractor/mfractor-feedback#2]
Hi
When I'm adding new event in Xaml  (Clicked for ex.) it offers to generate Code behind method (mfractor actions). After selecting offered option it does nothing.
And for some reason it duplicates option
![imagecut](https://user-images.githubusercontent.com/17849938/37649722-58e92ae2-2c3b-11e8-95e0-9f1ce0342f49.png)

**Comment by matthewrdev** [comment]
Thanks for the bug report, Yuriy. I'll look into it.

**Comment by yurkinh** [comment]
Fixed in v.3.04.15. Thanks
