### ISSUE TITLE
Import Image Wizard not opening on latest visual studio for mac update. v7.5.3 (Build 7)

### ISSUE THREAD

**Issue by EpicJoker93** [mfractor/mfractor-feedback#20]
After updating to latest visual studio for mac, mfractor import image wizard when clicked doesnt open the wizard. It just does nothing.

on Visual Studio for Mac 2017 v7.5.3 (build 7).

Thanks!

**Comment by jfversluis** [comment]
Yep, seeing that happen here as well (together with a colleague)

**Comment by sthewissen** [comment]
Same here, nothing opening anymore.

**Comment by jfversluis** [comment]
As a workaround for now, you could get an older version from here and install that manually: http://addins.monodevelop.com/Project/Index/300

**Comment by jfversluis** [comment]
3.05.17 which is downloadable now, fixes the problem 🎉

**Comment by EpicJoker93** [comment]
Saw that this morning! xD

Thanks gentleman.

**Comment by matthewrdev** [comment]
Hey @EpicJoker93, can I confirm that this is fixed?

**Comment by EpicJoker93** [comment]
@matthewrdev this is fixed.

**Comment by matthewrdev** [comment]
🎉
