### ISSUE TITLE
Request: Be able to suppress resource key conflicts on a file by file basis

### ISSUE THREAD

**Issue by anotherlab** [mfractor/mfractor-feedback#202]
The way I support dark mode in Xamarin.Forms apps is to put all of the color definitions in styles.  I have a dark style file and a light style file and I new them up at runtime based on the current theme.  MFractor detects that as a resource key conflict as the color names will be in two files.  Since the styles are loaded at runtime, I don't expect MFractor to be able to know there isn't an actual conflict.

![ResourceKey](https://user-images.githubusercontent.com/1191188/81838515-35a34b00-9514-11ea-8858-d40357478aa8.png)

What would be nice is some way to have a tag in a style file that basically says ignore it for resource key conflicts.  Kind of like the #pragma warning suppression that we have for C# files.  It would be a little hacky, but you could put a specific setting in as an XML comment.  

Something like:

**Comment by matthewrdev** [comment]
Hi Chris, thanks for the feedback.

I'll investigate getting this into the product. However, in the meantime, you can disable this analyser under Preferences by searching for MF1054:

![image](https://user-images.githubusercontent.com/3260473/81858035-73e94a80-95a6-11ea-86e2-9d61e127ceb8.png)

**Comment by matthewrdev** [comment]
Oops, actually the diagnostic ID is MF1044 - Resource Key Conflict.

**Comment by matthewrdev** [comment]
@anotherlab This is now implemented and will be available in v4.1.1. This should be released in the next few days.

![analyser-suppression](https://user-images.githubusercontent.com/3260473/82105660-d33e8a80-975f-11ea-886e-67f9bcd7bdda.gif)
