### ISSUE TITLE
Using Value Converter Wizard to add converter to page created duplicate xmlns

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#204]
I've got a xaml view that has the converters namespace declared `xmlns:converters="clr-namespace:ValueConverterSample.Converters"`.

When I run the value converter Wizard to generate another value converter I end up with it decclared twice which causes an error.
![2020-05-15 20 00 07](https://user-images.githubusercontent.com/29908924/82038630-288a8580-96e7-11ea-81cb-b59c5491ba64.gif)
![Screen Shot 2020-05-15 at 8 02 53 pm](https://user-images.githubusercontent.com/29908924/82038638-2aecdf80-96e7-11ea-86e6-28495d08df20.png)

VSMac 8.5.6, MFractor 4.1.0

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor 4.1.1.
