### ISSUE TITLE
404 for code action Learn how MFractor detects your ViewModels and Binding

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#205]
When I right click on a binding, it offers the code action "Learn how MFractor detects your ViewModels and Binding" which open the docs to https://docs.mfractor.com/xamarin-forms/configure-binding-context/?utm_source=Visual+Studio+Mac which gives a 404.

I think this link also used to be in the MVVM wizard somewhere but I can't find it now.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor v4.1.1.

**Comment by lachlanwgordon** [comment]
This refactoring seems to have disappeared so can't test if link works.  A lot of the places it we it used to be, it has been replaced with more useful things, probably related to bug #203.
