### ISSUE TITLE
Links don't work when mousing over an error

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#206]
In a Xaml file when you mouse over an error or warning it shows a list of available actions style as blue underline like a clickable link but clicking them does nothing.

It would be great if cilcking them worked, but I'm guessing this may not be possible in a tool tip so the styling should be removed to stop tempations.

This smells a little like a cross platforms issue where the links do work in Windows but can't work in Mac.

![Screen Shot 2020-05-15 at 8 11 22 pm](https://user-images.githubusercontent.com/29908924/82039659-a8fdb600-96e8-11ea-886d-d4b78fbd9410.png)

**Comment by matthewrdev** [comment]
I think I have resolved this in 4.1.1 by tweaking the first responder chain. Those inline fixes should work as they help tremendously when resolving issues.

I'll let you know when 4.1.1 is released Lachlan and get you to retest it. In the meantime I'm leaving this ticket open.

**Comment by matthewrdev** [comment]
@lachlanwgordon This is now released in MFractor 4.1.1. Can you retest it and let me know if it's still persisting?

**Comment by lachlanwgordon** [comment]
Confirmed fixed in MFractor 4.1.2 with VSMac 8.5.6(11)

**Comment by lachlanwgordon** [comment]
Something is still not quite right. 

Sometimes it will work with a single click, sometimes a triple-click is required, sometimes it will perform the action but the tooltip stays open and there's no idication that it did anything.

I think it works correctly 90% of the time. After restarting VS it will work correctly. If it fails then trying again will usually work.

Perhaps something todo with whether the editor window is properly focussed of if it's just open but focus is in one of the pads or has recently been in a popup.

**Comment by matthewrdev** [comment]
@lachlanwgordon Now that MFractors code actions integrated into the "Show potential fixes" area, it might be worth considering flat-out removing this feature as it's not working.

What do you think?

**Comment by lachlanwgordon** [comment]
I'm going to readjust the 90% estimate to 99% success rate. I think its useful enough and close enough to reliable to keep around.

**Comment by lachlanwgordon** [comment]
Not sure whether I'm meant to close this or you are, but I'm happy for it to be closed.
