### ISSUE TITLE
Binding Context Initialise in XAML sets x:Key instead of x:Name

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#207]
In the MVVM Wizard Project Settings, Set the Binding Context Initialisation to "Initialise BindingContext in XAML"
![Screen Shot 2020-05-15 at 8 18 00 pm](https://user-images.githubusercontent.com/29908924/82040221-9c2d9200-96e9-11ea-88ec-f0d78ebf84f3.png)

The Xaml it generates should have a `x:Name="ViewModel"` but instead sets `x:Key`

This results in a compile error as x:Key is only valid in a dictionary.

![Screen Shot 2020-05-15 at 8 19 28 pm](https://user-images.githubusercontent.com/29908924/82040237-a2bc0980-96e9-11ea-8a1d-72d4857dd905.png)

**Comment by matthewrdev** [comment]
This has been fixed and will be in the next release (4.1.1).
