### ISSUE TITLE
Go To ViewModel is not honouring x:DataType

### ISSUE THREAD

**Issue by pranshu-aggarwal** [mfractor/mfractor-feedback#209]
Go To ViewModel command is not working if x:DataType of page is set.

Please see the attachment for the issue with demo.

[MfractorDataTypeIssue.zip](https://github.com/mfractor/mfractor-feedback/files/4637953/MfractorDataTypeIssue.zip)

**Comment by matthewrdev** [comment]
@pranshu-aggarwal This has been fixed and will be in the next release (4.1.2).
