### ISSUE TITLE
About screen button has a typo

### ISSUE THREAD

**Issue by jfversluis** [mfractor/mfractor-feedback#21]
Button has a typo, detais instead of details

![image](https://user-images.githubusercontent.com/939291/41920325-c653b198-7960-11e8-8062-75d302d06b6c.png)

**Comment by orestesgaolin** [comment]
Also, it's 2018 now :D

**Comment by matthewrdev** [comment]
Ha! Thanks for spotting this Gerald. Onto fixing it for the next build.

**Comment by matthewrdev** [comment]
This will be fixed in MFractor v3.6 .

**Comment by matthewrdev** [comment]
Fixed and published in v3.5.22.
