### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by AlexHedley** [mfractor/mfractor-feedback#210]
On the Welcome screen some of the text is cut off.

![image](https://user-images.githubusercontent.com/1573469/82121169-e4e55980-9782-11ea-90bc-af54bce169e9.png)

Windows
VS 16.5.5

**Comment by matthewrdev** [comment]
This has been fixed and will be released in MFractor 4.2.6.

<img width="727" alt="Screen Shot 2020-06-25 at 8 04 55 am" src="https://user-images.githubusercontent.com/3260473/85632473-bf6d3900-b6ba-11ea-9078-0b047b44998b.png">
