### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#212]
It would be cool to have support for Blazor in MFractor. VSMac 8.6(currently in preview, stable in about a week) has much better support for Blazor including templates for web assembly.

## Core concepts
Blazor is a new Single Page Application framework from Microsoft, it can run sever side or client side with WASM. The project structure will vary slightly between the two but all the code is the same so there's probably no need to differentiate in MFractor.

In Blazor views are written in CSHTML a.k.a Razor syntax. This syntax has been used in ASP.Net MVC for years and is still used in dotnet core MVC. This means a lot of the features built for Blazor will also work for ASP.Net MVC. 

The views are in a file with the extensions .cshtml or .razor, they can be considered interchangeable.

 ## Code layout
A Razor page is a mix of C# and HTML. In general the top half of the file will be fairly close to HTML and there will be a code block at the bottom which is plain C#
![Screen Shot 2020-05-17 at 12 01 38 pm](https://user-images.githubusercontent.com/29908924/82134039-487c8f00-9836-11ea-8f9a-398de62426dd.png)

Anywhere you see an @ in the HTML section is Razor syntax which is what links the markup of HTML to the C# part of the world.

Example in the above screenshot include
* @page declares the page's route for navigation
* @using is the same as a using directive in C#
* @inject is the same as have an [Inject] attribute in C# to inject a dependency 
* @if lets you conditionally include/exclude content, the bit in brackets is a C# expression and has access to variables in the @code section
* @foreach is similar to @if for itterateively adding content
* the <td>@forecast...</td> elements are plain html but the content is accessing the value from a variable.

You can also write C# in line anywhere you feel like it with a lambda method @(() =>). This is often used to perform a null check or with a ternary operator when displaying a value. This is generally frowned upon for any more that a simple 1 liner.

The element <SurveyPrompt> is a Razor component, similar to a control. They appear inline as markup.  VSMac will place display the name in bold which is a hint that it's a Razor Component instead of an HTML element. There are some components built into Razor but they can also come from nugets or can be written in your project.

The code is basically HTML so it can also include JavaScript and CSS inline, although people would generally keep these in separate files rather than in the razor pages.

## MFractor actions
I'll create a new issue for each action as I think of it, but the kind of actions would include:
* Move inline C# to method
* Move inline style to CSS
* Generate Code behind
* Extract Component
* Resource navigation

**Comment by matthewrdev** [comment]
Going forward, MFractor will be focusing exclusively on the MAUI feature set. Going to close this and all web related features.
