### ISSUE TITLE
Blazor: Generate Code Behind

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#213]
In Razor syntax you can have all your code in one file or you can have it split into a .razor and a code behind .razor.cs, similar to Xamarin's .xaml and .xaml.cs.

For small pages it can be nice to have it all in one file but as it grows separating concerns becomes more important. The intellisense and design time errors work much better in a .cs file where it's only got one language to think about.

This page is part of the File>New template and has a varible and a method in the @code block

```
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
}
```

To split it you would create a new file called `Counter.razor.cs` which VS will automatically nest.

Everything inside the @code{} will be moved inside the code behind class. The code block can be deleted from the .razor. 

The code behind class needs to be a partial so it can be joined together with the .razor.

code will end up as 

```
using System;
namespace BlazorPwaTodo.Client.Pages
{
    public partial class Counter
    {
        private int currentCount = 0;

        private void IncrementCount()
        {
            currentCount++;
        }
    }
}
```

After extracting you will probably have lots of errors in both files saying the reference is ambiguouse/duplicated/missing. These can be ignored and will disappear after a succesful build.

In Razor pages using directives can be in two places, either at the top of the file or in the file _Imports.razor. Any usings in _Imports are available to all Razor pages but are not available in code behind.  Depending on what code you move across some of these usings may be needed. I'm not sure if you'll be able to add these automatically or if working out which ones are needed is to hard and the user may have to do it manually. 

This is the default _Imports.razor on a new project, this will typically grow a lot.
```
@using System.Net.Http
@using System.Net.Http.Json
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.WebAssembly.Http
@using Microsoft.JSInterop
@using BlazorPwaTodo.Client
@using BlazorPwaTodo.Client.Shared
```

**Comment by lachlanwgordon** [comment]
It probably makes sense to present this when you right click on @code or if you right click on the file in the solution explorer.

**Comment by matthewrdev** [comment]
@lachlanwgordon Can a razor file have multiple `@code` sections defined?

**Comment by ravero** [comment]
Yes.

**Comment by matthewrdev** [comment]
**Technical Investigation**
Visual Studio declares the Razor content type that we can use to detect this kind of syntax. Additionally, we can leverage the Razor syntax service to explore and refactor a users code. See: https://github.com/dotnet/aspnetcore/tree/66dd4919dafcb21c57a923a661cdbb0ff351713d/src/Razor/Microsoft.AspNetCore.Razor.Language

We will need to figure out how to access the syntax tree to enable this feature group.

**Comment by matthewrdev** [comment]
Going forward, MFractor will be focusing exclusively on the MAUI feature set. Going to close this and all web related features.
