### ISSUE TITLE
Blazor: MVVM Wizard

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#215]
Just like the XAML one but it generates a .razor and a .razor.cs instead

It looks like you already decide which wizards are available from the menu based on the current active project.

e.g. a new page called users
Name: Users

The view would be file would be UsersPage.razor
```
@page "/users"
```
The code behind would be UsersPage.razor.cs
```
using System;

namespace ProjectNameSpace.Pages
{
    public partial class UsersPagerazor
    {
    }
}
```

The ViewModel will be exactly the same as in the Xamarin Forms version.

The Project MVVM Settings would need a couple of changes:
* View Base Class can be removed
* View Base Class XML Namespace can be removed
* Binding Context Initialisation will have three options
** No Binding Context Initialisation
** Initialise Binding Context in Code Behind. This would add a property `UsersPageViewModel ViewModel = new UsersPageViewModel;` and the appropriate Using Directive.
** Inject ViewModel in Code Behind. 
*** This would add the line to the code behind `[Inject] UsersViewModel ViewModel { get; set;}`, 
*** add a using for the ViewModel namespace 
*** add `using Microsoft.AspNetCore.Components;`. 
*** Register the ViewModel for DI.  If it's a Blazor WASM project this is (usually) in Program.cs, you'd add the line `builder.Services.AddTransient<UsersPageViewModel>();`. If it's serverside blazor you'll  add it in Startup.cs(probably) and the line will be `services.AddTransient<UsersPageViewModel>();`

**Comment by matthewrdev** [comment]
Going forward, MFractor will be focusing exclusively on the MAUI feature set. Going to close this and all web related features.
