### ISSUE TITLE
.ctor not being renamed when using clipboard class tool

### ISSUE THREAD

**Issue by stntz** [mfractor/mfractor-feedback#218]
I used the ‘Add Class Using Clipboard’ tool and I was able to rename the class as I was doing a duplicate copy.

Class renamed fine but I had to manually change the constructors. 
Can we have a way to make sure this changes too.

**Comment by matthewrdev** [comment]
@stntz This has been fixed and will be available in MFractor 4.2 (released next week).

Demo:
![clipboard-tooling-fixes](https://user-images.githubusercontent.com/3260473/82505600-779a4580-9b41-11ea-9c60-2e247edaade1.gif)
