### ISSUE TITLE
MFractor doesn't check for Android Vector Drawable files when validating images

### ISSUE THREAD

**Issue by anotherlab** [mfractor/mfractor-feedback#219]
MFractor is reporting that an image doesn't exist in Android. I think this is happening because it's not checking for Android Vector Drawables, only for bitmaps.   I have a Xamarin.Forms app that has a logo used as an image.  For iOS, I use a .png (with Retina sizes) and on Android I use a vector drawable with the .xml extension.  The screenshot below shows the message from MFractor and I put an arrow to show that image is in the Android project's Resources\Drawable folder.

![mfactor-avd](https://user-images.githubusercontent.com/1191188/82473387-7c0a2400-9a97-11ea-8034-9629b2d17d40.png)

--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 19.4.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.1.0.0
Product Variant: Visual Studio Mac
Product Variant Version: 8.5.5.7

**Comment by matthewrdev** [comment]
Good catch Chris!

**Comment by matthewrdev** [comment]
@anotherlab This has been fixed and will be available in MFractor v4.2 (available next week).
