### ISSUE TITLE
Delete Row/Column negative index

### ISSUE THREAD

**Issue by AlexHedley** [mfractor/mfractor-feedback#220]
When deleting the first row/column the the index is changed to a negative one
- `Grid.Row="-1"`
- `Grid.Column="-1"`

![delete-row-negative-index](https://user-images.githubusercontent.com/1573469/82539642-ac100080-9b45-11ea-9b6e-7bf882761a75.gif)

**Comment by matthewrdev** [comment]
@AlexHedley This has been fixed and will be available in MFractor 4.2 (due early next week).

**Comment by AlexHedley** [comment]
Will it just set them to 0?

**Comment by matthewrdev** [comment]
Yes, it will leave items at index 0 rather than decrement them.
