### ISSUE TITLE
VS Mac freezing/not responding

### ISSUE THREAD

**Issue by rickdijk** [mfractor/mfractor-feedback#221]
Since the latest update I've been experiencing VS Mac freezing when working in xaml files.
Mostly happening when saving a xaml file or when looking up a static resource.
Our styles.xaml file is particularly big, which might be the cause of the problem, but I can't be completely sure.

I turned off the adornments earlier in the settings and that made the problem appear less often, but I'm still experiencing this issue nearly once an hour.

### Specs
- VS Mac stable version 8.6 (build 4520)
- Latest stable version of MFractor
- Xamarin Forms latest version
- MacBook Pro 2018 with MacOS Catalina 10.15.4

Disabling the MFractor extension is currently the only way to prevent the freezing, as far as I know.

**Comment by matthewrdev** [comment]
@rickdijk I've resolved several memory and event leaks in the core engine that *should* help address this issue. These fixes will be available in MFractor 4.2, released tomorrow or Thursday AEST.

**Comment by rickdijk** [comment]
> @rickdijk I've resolved several memory and event leaks in the core engine that _should_ help address this issue. These fixes will be available in MFractor 4.2, released tomorrow or Thursday AEST.

Thanks for the quick response!
