### ISSUE TITLE
Enter Key Submit in Scaffolder

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#223]
Here's a quick win(I think)

When using the Scaffolder, I enter in a name. A lot of the time the first item in the list is what I want. If I then hit 'Enter' It should be the same as clicking 'Generate'. This will make the Scaffolder super fast to use.

Sometimes I want the second or third Item in the list. Hitting the down/up arrow is intuitive and lets you select the item you want. This already works(awesome), If you've done this the 'Enter' key should still work to generate what ever is selected.

If this isn't easy, perhaps a tweak to Tab sequence would be a nice half-measure, ideally both I guess but tab sequence is less important if you can do everything with out it.

**Comment by matthewrdev** [comment]
@lachlanwgordon This is great feedback and should be pretty easy to implement. Will aim to get this done over the weekend and released early next week.

PS: Please suggest as many scaffolds as you would like by the way as they are dead easy to make. Include the rules (naming conventions, file extensions, project context) and a sample of the code and I can get them made.

**Comment by matthewrdev** [comment]
This will be available in MFractor 4.2.1, available early this afternoon.
