### ISSUE TITLE
Scaffolder Tab Sequence

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#224]
Scaffolder is awesome but I want to use it without the mouse. I've proposed a ver fast way to use it in #223 but if that doesn't work, here's an alternative.

At the moment tab Sequence goes Class Entry > Template Selector > Drop Down With File Name(this drop down does nothing? So shouldn't be tabbable?) > Code Preview(Not editable so shouldn't be tabbabel?) > Off into the either... Never gets to Generate

Proposed alternative would be Class Entry > Template Selector > Generate Button > Loop back to start.

**Comment by matthewrdev** [comment]
@lachlanwgordon This should be addressed by #223 (available in 4.2.1). Can you test the new build and then close this ticket if you are happy with it? :)

**Comment by lachlanwgordon** [comment]
#223 Enter key works nicely so I'm happy
