### ISSUE TITLE
Scaffolder Hot Key

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#225]
I want a hot key so i can access the Scaffolder without touching the mouse. If you can get this working in conjunction with #223 File/Folder creating will be 10x or maybe 50x faster than default VS experience.

I found in the VS Mac the keybinding entry for the Scaffolder but no matter what key combination I set for it I can't get it to open. I've made sure there are no conflicts.

A default hot key could be nice but the curstom one working will be good enought if you can think of something intuitive that's unlikely to clash, adding something this late in the game may make people angry if you break their workflow. 

This may well be a VS Mac bug or some other conflict on my system but I have set up other keybinding successfully. If you think it's a broader issue can you offer any insight or context that I can add when filing a VS Mac bug?

**Comment by matthewrdev** [comment]
@lachlanwgordon The scaffolder is setup to launch via the solution pad, however, MFractors integration may also expose that command via general commanding menu. Without the solution pad context, it won't be able to launch (an API restriction in MFractor). This will requires some changes to the engine, I'll have a think about how to expose this.

What key-binding have you setup for the Scaffolder?

**Comment by lachlanwgordon** [comment]
I reckon Command+Alt+N is the best option

For the letter part I think S for Scaffold, N for New or A for Add make sense.

For the modifiers, you already use Command+Alt+1/2/3 for file navigation so it would kind of make sense to follow that pattern and put other MFractor actions in the Command+Alt group. I suppose that translates in the VSWindows world.

Command+Alt+A is Add FIles in VS Mac by default so you can't have that, Command+Alt+S is save all.

**Comment by matthewrdev** [comment]
@lachlanwgordon That keyboard combination makes a lot of sense (like you said, it continues with our conventions).

**Comment by matthewrdev** [comment]
This has been implemented using `Alt+Shift+N` and will require a document to be open in order for the scaffolder to launch.

It will take additional work to create a project selector, can you please open an additional issue for this?

**Comment by matthewrdev** [comment]
This will be available in MFractor 4.2.1, available early this afternoon.
