### ISSUE TITLE
I miss alt enter in xaml

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#226]
I'm guessing you're well aware of this and that it's out of your control since the new editors.

Life was much simpler when I could press alt+enter in any code and it would MFractor actions along side the built in refactorings. Is there any way to bring this back? Reaching for the mouse greatly reduces discoverability.

If you can't get them mixed in with Alt+Enter, how about something like Command+Alt+Enter to open the MFractor Code Actions?

**Comment by matthewrdev** [comment]
@lachlanwgordon Can you try this in the MFractor 4.2 release? This *should* now be exposed but would like to confirm.

**Comment by lachlanwgordon** [comment]
Hooray, this works!

**Comment by matthewrdev** [comment]
Can I close this ticket @lachlanwgordon?

**Comment by lachlanwgordon** [comment]
Sure thing, I'm happy with it :)
