### ISSUE TITLE
Delete Images not Working on Windows

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#228]
The Delete Images feature is not working on Windows. When you select a image on the _Image Asset Manager_ tool window and clicks on delete button nothing happens.

**Comment by matthewrdev** [comment]
This sounds like a bug in the display code for the dialog (see DeleteImageAssetWorkUnit). Will need to investigate the UI threading for the work unit handler and make sure it is behaving as expected.

**Comment by matthewrdev** [comment]
Duplicate of #253. This has been fixed in MFractor 4.2.4.
