### ISSUE TITLE
Color Tooltips are behaving inconsistently for Setters

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#230]
The color Tooltip doesn't always appear on every spot where the color adornment appears. A few screenshots to exemplify:

![Screen Shot 2020-05-26 at 21 56 33](https://user-images.githubusercontent.com/1834963/82964416-ce69aa00-9f9b-11ea-930f-664ca28a76eb.png)
![Screen Shot 2020-05-26 at 21 56 42](https://user-images.githubusercontent.com/1834963/82964428-d295c780-9f9b-11ea-91ae-935aaa29a966.png)

There you can see that for the same XAML file tooltips appears for colours from Static Resources but not from raw color values. Before I tried to reproduce this error the exact opposite was happening (raw colours rendered Tooltips while color Static Resouces doesn't).

It's important to note that this inconsistent isn't always reproducible. So there's probably something happening on the engine that resolves Tooltips. Color adornments on the other hand always appear, so base on how the color adornment places are being resolve is good start trying to find those inconsistencies.

**Comment by matthewrdev** [comment]
This is because the symbol resolver is not functioning for Setters. Will need to update the XAML symbol resolvers behaviour to also return symbolication data for setter colors and then this should work correctly for tooltips.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor 4.2.2.

<img width="714" alt="Screen Shot 2020-06-04 at 7 02 14 pm" src="https://user-images.githubusercontent.com/3260473/83737173-fd67d600-a695-11ea-847f-e4e2a4639933.png">
