### ISSUE TITLE
No Refactor Menu Item on XAML Page

### ISSUE THREAD

**Issue by roteague** [mfractor/mfractor-feedback#238]
##Installation Information

```
--Platform Information--
Operating System: Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.18362.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.2.0.0
Product Variant: Visual Studio For Windows
Product Variant Version: 16.0.0.0
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 456a155ffb822243ae788e1ff912fa28be4af2e3
Revision: 4363
Branch: master
Date: 12/05/2020 2:26:45 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
Hi @roteague, thanks for logging this issue.

I'll need a little bit more clarification on this to help resolve this issue. What is the expected menu that is not present? On Window, MFractor does not surface a refactor/MFractor Code Actions menu as our code actions are available through the Quick Fix menu (Alt+Return or the Screwdriver menu).

If possible, could you attach a screenshot that demonstrates where this menu should be?

**Comment by roteague** [comment]
Cursor is on Stack Layout using Alt+Enter gives this

Below the Stack Layout

Gives the Resharper Menu

As you can see, MFractor is loaded:

No screwdriver or light bulb quick actions. I only noticed this when I wanted to convert the StackLayout to a Grid.

Thanks,

Robert

----------------------------------------

**Comment by matthewrdev** [comment]
Hi Robert, I can't see any screenshots in you reply (if there were included that is). Could comment directly against the GitHub issues and attach them.

Also, you can follow this guide to ensure that MFractor works alongside ReSharper: https://docs.mfractor.com/resharper-compatibility/

**Comment by roteague** [comment]
Hi,

I'm not sure why the attachments got stripped out of the email, so I've attached them as a zip file to this email. It looks like the Resharper was interfering with it. I made changes to the settings and got the menu to show up, with the StackLayout refactoring. So thanks for all your help.

Robert

----------------------------------------

**Comment by matthewrdev** [comment]
Fantastic to hear Robert.

Can I confirm this is now working as expected and that I can close this issue?

**Comment by roteague** [comment]
Yes, please.




Thanks, 




Robert 




Sent from my T-Mobile 4G LTE Device







On Wed, Jun 3, 2020 at 6:12 PM -0700, "Matthew Robbins" <notifications@github.com> wrote:















Fantastic to hear Robert.


Can I confirm this is now working as expected and that I can close this issue?
