### ISSUE TITLE
Scaffolder list incorrect if i use .razor.cs extension

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#239]
There are a couple of issues that show up related to .razor.cs, I'll make them as separate issues even though they may be related.

When I enter a file name `BadPage.razor.cs` the list shows "Create a Razor component with a code behind class" twice, one of these should say "Create a Razor component with a code behind class"

![Screen Shot 2020-06-04 at 12 02 29 pm](https://user-images.githubusercontent.com/29908924/83706766-b0ffa480-a65b-11ea-8727-46c16f0cb5b6.png)

The second entry does have the `@page` directive so it does link to a different action.

![Screen Shot 2020-06-04 at 12 06 14 pm](https://user-images.githubusercontent.com/29908924/83706824-d12f6380-a65b-11ea-8e5f-4c44612a8fe6.png)

**Comment by matthewrdev** [comment]
This has been fixed and will be released in MFractor 4.2.2.
