### ISSUE TITLE
XAML intellisense doesn't work (3.05.18 @ VS 7.5.4.3)

### ISSUE THREAD

**Issue by orestesgaolin** [mfractor/mfractor-feedback#24]
# Problem

While using XAML editor I don't get any reasonable autocomplete/intellisense. Please see attached gifs for reference.

![screencast 2018-07-27 22-30-12](https://user-images.githubusercontent.com/16854239/43345201-d745c668-91ec-11e8-9a26-09f0c7bd6d31.gif)
![screencast 2018-07-27 22-29-24](https://user-images.githubusercontent.com/16854239/43345208-d9171db6-91ec-11e8-9b76-a3db6063c533.gif)

> --Platform Information--
> Operating System: Mac
> OS Version: 10.13.6
> --MFractor Information--
> Product Name: MFractor
> Product Version: 3.05.18
> Product Variant: Visual Studio For Mac
> Product SKU: MFRACTOR-VS-MAC
> Commit SHA: 924cea71e8caeb56c6dee03cf3fa3d8425d84cfa
> Revision: 2455
> Branch: master
> Date: 2/07/2018 6:01:31 AM (UTC)
> Agent: Local
> --IDE Information--
> Mono Version: 5.10.1.57 (2017-12/ea8a24b1bbf)
> Runtime Version: 7.5.4.3
> IDE Version: 7.5.4.3
> IDE Product is: Visual Studio
> Installed addins:
> 	'EditorConfig', 'MFractor', 'NuGet Package Management Extensions', 'Mutatio', 'Prism Template Studio and Developer Toolkit', 'Gorilla Player', 'DeepClean', 'Internet of Things (IoT) development (Preview)', '.Net Core Debugger', 'Razor Language Services', 'Web Editors', 'Web Project Support', 'ASP.NET Core Support', 'MonoDevelop Assembly Browser', 'Makefile generation', 'Azure Functions development (Preview)', 'CSharp Language Binding', 'ChangeLog Add-in', 'ConnectedServices', 'Debugger support for MonoDevelop', 'Mono Soft Debugger Support', 'Mono Soft Debugger Support for ASP.NET', 'VsCode Debug Protocol support for MonoDevelop', 'Deployment Services Core', 'Deployment Services for Linux', 'Visual Designer Support', 'DocFood', 'Container Tools', '.NET Core Support', 'F# Language Binding', 'Gettext Translations Support', 'GTK# Visual Designer', 'MonoDevelop Hex Editor', 'ILAsm Language Binding', 'iOS development', 'Mac Development', 'MonoDevelop Mac Platform Support', 'Android development', 'IDE Extensions for developers of the Mono framework', 'Xamarin.Mac development', 'NuGet Package Management', 'NuGet Packaging', 'Performance Diagnostics of IDE', 'Refactoring Support', 'Regex Toolkit', 'MonoDevelop Source Editor', 'Test Runner', 'Text Templating', 'Unit Testing core support', 'NUnit support', 'Visual Studio for Mac Tools for Unity', 'VB.NET Language Binding', 'Version Control Support', 'Git support', 'Subversion core engine', 'Subversion support', 'Project Web References', 'Xamarin Ide Extensions', 'Xamarin Ide Extensions for Mac', 'XML Editor', 'Android Designer', 'Azure Mobile App Service', 'Azure Support', 'Xamarin Designer', 'Forms Project Support', 'Forms Previewer', 'Xamarin Ide Identity', 'Xamarin Ide Insights', 'Xamarin Inspector Support', 'IoT development', 'Xamarin Live Player', 'Xamarin Test Cloud', 'Xamarin Test Cloud - NUnit', 'iOS Designer'

**Comment by orestesgaolin** [comment]
I realized that XAML works for some solutions while not for the other. Here is a sample solution that breaks the XAML intellisense https://github.com/orestesgaolin/PlaygroundApp/tree/d367d2b046de9e0ec069c138116f9d1a88adb597

**Comment by matthewrdev** [comment]
Hi @orestesgaolin, could you please re-test this with v3.5.21?

We have worked through and fixed multiple bugs in our XAML editor, this should hopefullly address your issues.

**Comment by orestesgaolin** [comment]
Thanks @matthewrdev. The issue is no longer present thus we can consider it fixed and closed :) Also all the main tooltips and refactorings seem to work fine 👍
