### ISSUE TITLE
Deactivate License Bug

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#240]
When clicking on the Deactivate License button from the MFractor Licensing dialog, the text needs to be updated. This is what is being displayed currently, **"Are you sure you want to deat your current license? /m ,eactiv a license is permanent and non-recoverable."**

**Comment by geniesoftstudios** [comment]
@matthewrdev This issue seems to be happening within MFractor for Windows as well.

**Comment by matthewrdev** [comment]
@geniesoftstudios This is fixed and will be available in MFractor 4.2.2.
