### ISSUE TITLE
When using .razor.cs extension with scaffolder, it creates a .razor file but no code behind for pages

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#241]
I enter `something.razor.cs`, select the second "Create a Razor component with a code behind class" and click "Generate".  The second one is the one that adds `@page`

![Screen Shot 2020-06-04 at 12 28 53 pm](https://user-images.githubusercontent.com/29908924/83708230-2325b880-a65f-11ea-9231-0099f0ba6ee0.png)

In my solution I've got a .razor but no .razor.cs
![Screen Shot 2020-06-04 at 12 29 14 pm](https://user-images.githubusercontent.com/29908924/83708329-65e79080-a65f-11ea-92a8-b92cb0c610b7.png)

**Comment by matthewrdev** [comment]
This has been fixed and will be released in MFractor 4.2.2.
