### ISSUE TITLE
Scaffolder .razor.cs strange class names

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#243]
If I use the Scaffold item `Create a Razor component with a code behind classs`(the first one, for components). 

The code behind it generates  has the correct file name but the class is called `BadPage.razor` which causes a compile error.

The Constructor just has `razor()`

![Screen Shot 2020-06-04 at 12 37 00 pm](https://user-images.githubusercontent.com/29908924/83708653-1bb2df00-a660-11ea-9193-da62fe4b94a6.png)

**Comment by matthewrdev** [comment]
Well, looks like I rushed this and missed some sanitisation!

**Comment by matthewrdev** [comment]
This has been fixed and will be released in MFractor 4.2.2.
