### ISSUE TITLE
URL incorrect for scaffolding .razor.cs

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#244]
I used the scaffolder to create a page with code behind. The URL in the `@page` includes .razor.

![Screen Shot 2020-06-04 at 12 38 56 pm](https://user-images.githubusercontent.com/29908924/83708875-a5fb4300-a660-11ea-805c-f678445267bf.png)

**Comment by matthewrdev** [comment]
This has been fixed and will be released in MFractor 4.2.2.
