### ISSUE TITLE
Create a tools menu command that can add an ExportFont declaration for a font file.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#249]

**Comment by ravero** [comment]
Can you provide further details on how you expect this to work?
I'm little confused by what you're referring to as "ExportFont declaration". Is it the declaration of the font static resources, the declaration on Info.plist?

**Comment by matthewrdev** [comment]
This is specifically for the new embedded font methodology of adding fonts to a Xamarin.Forms project.

See: 
 - https://devblogs.microsoft.com/xamarin/embedded-fonts-xamarin-forms/
 - https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.exportfontattribute?view=xamarin-forms

**Comment by matthewrdev** [comment]
Released in MFractor 4.2.4.
