### ISSUE TITLE
MVVM Wizard is disabled unless a file is opened

### ISSUE THREAD

**Issue by stephenhauck** [mfractor/mfractor-feedback#251]
MVVM Wizard is disabled unless a file is opened for editing.
But then it seems to stay available after the files are closed even after closing Visual Studio and relaunching.

![image](https://user-images.githubusercontent.com/12648793/84328586-57faa980-ab50-11ea-9ee6-a740a008067f.png)

**Comment by matthewrdev** [comment]
Technical note: This feature uses the `IActiveDocument` to provide the targetted project to generate the MVVM component for. To resolve this dependency, we should launch a project selector to allow the user to choose the project. Alternatively, we should build a project selector into the MVVM wizard.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor v4.2.9.

**Comment by stephenhauck** [comment]
AWESOME, thanks!
