### ISSUE TITLE
Deactivate License Text Bug not appearing on a new line.

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#252]
When clicking on the Deactivate License button from the MFractor Licensing dialog, the text needs to be updated as this shows the following, "Are you sure you want to deactivate your current license?/nDeactivating a license is permanent and non-recoverable." The "/nDeactivating a license is permanent and non-recoverable" should be on a new line which is not happening.

**Comment by matthewrdev** [comment]
@geniesoftstudios This has been fixed and will be available in MFractor 4.2.4.
