### ISSUE TITLE
Navigate to ViewModel doesn't work if it's in a different project

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#254]
If the ViewModel is in a different project to the View, the Alt+Shift+1/2/3 hotkeys don't work.

I like to keep my ViewModels and any other code that doesn't depend on Xamarin Forms in a separate .NetStandard library from my Forms Views so they can be reused in my Blazor code and so the models can be used on the server.

If you check out this repo https://github.com/lachlanwgordon/MelbourneModernApps repo, open any view or viewmodel and try to use the hotkeys it won't work.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor v4.2.4.
