### ISSUE TITLE
Import Image Asset doesn't work in very large solutions

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#257]
I'm working in a solution with 54 projects. It's a fork of Xamarin Forms with a few extra projects.

https://github.com/lachlanwgordon/Xamarin.Forms.NewFeaturesDemo/tree/MeetupDemo

When I open Assett Manager it loads the list of assetts fine, but when I click Import New Image Asset nothing happens. It could be something else about the repo rather than the size that's breaking it, I'm not sure.

I regularly use it in a solution with 11 projects with no issues.

This is probably quite low priority as it may not be affecting many people, and it's not something I need to do often.

![2020-06-16 22 51 53](https://user-images.githubusercontent.com/29908924/84776899-41f35a00-b024-11ea-9aec-6113c2a257b8.gif)

VS Mac 8.6.2, MFractor 4.2.3

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been resolved and will be available in MFractor 4.2.9.
