### ISSUE TITLE
Delete Ouput Folders does not delete obj folder

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#259]
In VS Mac I right click on a project or solution and select 'Delete Output Folders'. I have Bin and Obj selected but when I check in Finder the OBJ folders are still there.

![2020-06-17 11 37 59](https://user-images.githubusercontent.com/29908924/84845167-50c32680-b08f-11ea-909c-d216fa2fb2f1.gif)

VS Mac 8.6.2
MFractor 4.2.3

**Comment by matthewrdev** [comment]
@lachlanwgordon If you have chosen to *not* delete the nuget packages then MFractor will preserve the `project.assets.json` and `project.nuget.cache` files. Can you verify if the internal Debug and Release folders are being deleted?

**Comment by lachlanwgordon** [comment]
Oh cool, my bad. Yes, it deletes the Debug folder, and if you select Packages it does delete the whole OBj folder.
