### ISSUE TITLE
Cant see Replace with a localised value lookup.

### ISSUE THREAD

**Issue by blombas** [mfractor/mfractor-feedback#26]
I have a problem with localization and mfractor. For some reason I don't see Replace with a localised value lookup. when i right click. I have bought a pro license and I am using Prism Quickstart with Mfractor.Config. Under tools i can see mfractor tools is grayed out.

**Comment by matthewrdev** [comment]
Hi @blombas, thanks for reporting this issue.

What version of both Visual Studio Mac and MFractor are you running?

Please go to the **About Visual Studio** menu item in the top navigation bar, click **Show Details** and then click **Copy Information**. This will copy the version information into your clipboard. Please paste that into this ticket.

Next, could you please upgrade both Visual Studio Mac and MFractor. At the time of writing MFractors current version is 3.5.21.

**Comment by matthewrdev** [comment]
@blombas I'm going to close this as it's working as expected in the latest version of MFractor (v3.2.22). If this issue is still persisting, please re-open this ticket.
