### ISSUE TITLE
Intellisense and MergedDictionaries

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#261]
Hi 
I use a MergedDictionary which is defined in the App.Xaml like so:
`      <ResourceDictionary>
          <ResourceDictionary.MergedDictionaries>
              <ResourceDictionary Source="Resources/Styles/Base/BaseStyles.xaml"/>
          </ResourceDictionary.MergedDictionaries>
      </ResourceDictionary>`
This works, however the intellisense doesn't seem to recognize the definitions correctly.
please see the attached image for the somewhat curious message I'm getting (basically it's saying 'A' not recognized, should I replace it with 'A' ?)
**NB. It works when placing a space behind the symbol (eg Style="{StaticResource PrimaryButtonStyle }"**

<img width="843" alt="Screenshot 2020-06-22 at 09 47 44" src="https://user-images.githubusercontent.com/13586354/85262831-9b1d1c80-b46e-11ea-9e19-846401e1f9fb.png">

**Comment by matthewrdev** [comment]
@MBrekhof Are you able to provide a minimum reproduction sample? I've attempted to create a reproduction case based on your description above however I am unable to reproduce this locally.

<img width="1666" alt="Screen Shot 2020-06-24 at 7 42 03 am" src="https://user-images.githubusercontent.com/3260473/85467243-4dc7b900-b5ee-11ea-9495-6b7346af1fb1.png">

**Comment by MBrekhof** [comment]
Made a demo app and couldn't reproduce the problem :-) Problem seems also to be gone in the program I was experiencing it in. Not sure about the how/why but case closed I think.

**Comment by matthewrdev** [comment]
`"Case closed"` <- Words guaranteed  to make me a happy man.
