### ISSUE TITLE
Intellisense and Picker

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#262]
Hi 
Using a picker in Forms I would appreciate the properties for ItemDisplayBinding being recognized and available in the intellisense popup. Now it flags a correct property name as wrong which is somewhat problematic at times.

regards

**Comment by matthewrdev** [comment]
@MBrekhof This has been fixed and will be available in MFractor v4.2.6.

<img width="775" alt="Screen Shot 2020-06-23 at 8 57 08 pm" src="https://user-images.githubusercontent.com/3260473/85395889-2b08b680-b594-11ea-9ee5-6ec7b574752c.png">

<img width="704" alt="Screen Shot 2020-06-23 at 8 57 00 pm" src="https://user-images.githubusercontent.com/3260473/85395926-39ef6900-b594-11ea-8940-9db68cce0261.png">
