### ISSUE TITLE
Windows: License dialog displays the serial key entry.

### ISSUE THREAD

**Issue by AlexHedley** [mfractor/mfractor-feedback#263]
If you register your license then go to the **Licensing Information** screen, there is a stray label in the top left hand corner of the popup

> "Paste your serial key here..."

![image](https://user-images.githubusercontent.com/1573469/85394381-67adc100-b546-11ea-8316-6bb2e47904a0.png)

Version 4.2.5 (Build 4363 | 456a155f)

![image](https://user-images.githubusercontent.com/1573469/85394425-75634680-b546-11ea-94bc-53b9f20c7bf6.png)

**Comment by ravero** [comment]
Checking on this ...

**Comment by matthewrdev** [comment]
@AlexHedley @ravero I've played around with the UI layout here and worked around the XWT bug that caused this. 🤷‍♂️
