### ISSUE TITLE
Scaffold Page/ContentPage

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#266]
When I use the scaffolder to make a new xaml page with CodeBehind it creates a `Page`, but I always want a `ContentPage`. 

I don't think anyone really uses Page, it's basically an Abstract Class for other pages to inherit from.

Can we swap it so that it generates ContentPages instead, or if there's some good reason I'm missing to use page, create ContentPage as an extra option?

**Comment by ravero** [comment]
@lachlanwgordon I agree with that I doesn't make much sense to base on the abstract `Page`.
I've already fixed that on an internal build, waiting on @matthewrdev approval to release the update on the next version.

**Comment by matthewrdev** [comment]
@lachlanwgordon This is published in MFractor 4.2.7.
