### ISSUE TITLE
Generate localization infrastructure

### ISSUE THREAD

**Issue by mikehachen** [mfractor/mfractor-feedback#27]
Hi there

Generating localization infrastructure does not work correctly. After starting the process via context menu mfractor creates a new folder called i18n, adds interface ILocalise and class TranslateExtension. In both platform projects (iOS and Android) there is a class created called Localise. This class implements the ILocalise interface. After adding those classes I get an empty error windows:
![screen shot 2018-09-08 at 12 53 18](https://user-images.githubusercontent.com/7340450/45253406-dd8f6b00-b366-11e8-9a5f-5c426215b007.png)

The Implementation of the platform specific classes (Localice.cs) is not complete. Here is the complete code which is added automatically (Android):
`using System;
using System.Globalization;
using System.Linq;
using System.Threading;
using Java.Util;
using JostMobile.Droid;
using JostMobile.i18n;
using Xamarin.Forms;

[assembly: Dependency(typeof(Localise))]

namespace JostMobile.Droid
{
    public class Localise : ILocalise
    {
        public void SetLocale(CultureInfo ci)
        {
            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = ci;
        }

        public CultureInfo GetCurrentCultureInfo()
        {
            var netLanguage = "en";
            var androidLocale = Java.Util.Locale.Default;
            netLanguage = AndroidToDotnetLanguage(androidLocale.ToString().Replace("_", "-"));
            // this gets called a lot - try/catch can be expensive so consider caching or something
            CultureInfo ci = null;
            try
            {
                ci = new CultureInfo(netLanguage);
            }
            catch (CultureNotFoundException e1)
            {
                // iOS locale not valid .NET culture (eg. "en-ES" : English in Spain)
                // fallback to first characters, in this case "en"
                try
                {
                    var fallback = ToDotnetFallbackLanguage(new PlatformCulture(netLanguage));
                    ci = new CultureInfo(fallback);
                }
                catch (CultureNotFoundException e2)
                {
                    // iOS language not valid .NET culture, falling back to English
                    ci = new CultureInfo("en");
                }
            }
            return ci;
        }
        string AndroidToDotnetLanguage(string androidLanguage)
        {
            var netLanguage = androidLanguage;
            //certain languages need to be converted to CultureInfo equivalent
            switch (androidLanguage)
            {
                case "ms-BN":   // "Malaysian (Brunei)" not supported .NET culture
                case "ms-MY":   // "Malaysian (Malaysia)" not supported .NET culture
                case "ms-SG":   // "Malaysian (Singapore)" not supported .NET culture
                    netLanguage = "ms"; // closest supported
                    break;
                case "in-ID":  // "Indonesian (Indonesia)" has different code in  .NET
                    netLanguage = "id-ID"; // correct code for .NET
                    break;
                case "gsw-CH":  // "Schwiizertüütsch (Swiss German)" not supported .NET culture
                    netLanguage = "de-CH"; // closest supported
                    break;
                    // add more application-specific cases here (if required)
                    // ONLY use cultures that have been tested and known to work
            }
            return netLanguage;
        }
        string ToDotnetFallbackLanguage(PlatformCulture platCulture)
        {
            var netLanguage = platCulture.LanguageCode; // use the first part of the identifier (two chars, usually);
            switch (platCulture.LanguageCode)
            {
                case "gsw":
                    netLanguage = "de-CH"; // equivalent to German (Switzerland) for this app
                    break;
                    // add more application-specific cases here (if required)
                    // ONLY use cultures that have been tested and known to work
            }
            return netLanguage;
        }
    }
    }
}
`
First, there is one } too much at the end. Second, the ILocalise Interface is not fully implemented (function void SetLocale() is missing).
Third there is no class called 'PlatformCulture' created. 

Same is true for the class Localise in the iOS platform project. SetLocal() is missing and there is no 'PlatformCulture' class. 

--Platform Information--
Operating System: Mac
OS Version: 10.13.4
--MFractor Information--
Product Name: MFractor
Product Version: 3.05.18
Product Variant: Visual Studio For Mac
Product SKU: MFRACTOR-VS-MAC
Commit SHA: 924cea71e8caeb56c6dee03cf3fa3d8425d84cfa
Revision: 2455
Branch: master
Date: 2/07/2018 6:01:31 AM (UTC)
Agent: Local
--IDE Information--
Mono Version: 5.12.0.301 (2018-02/4fe3280bba1)
Runtime Version: 7.6.3.1
IDE Version: 7.6.3.1
IDE Product is: Visual Studio
Installed addins:
	'MFractor', 'Team Foundation Version Control for TFS and VSTS', 'Internet of Things (IoT) development (Preview)', '.Net Core Debugger', 'Razor Language Services', 'Web Editors', 'Web Project Support', 'ASP.NET Core Support', 'MonoDevelop Assembly Browser', 'Makefile generation', 'Azure Functions development', 'CSharp Language Binding', 'ChangeLog Add-in', 'ConnectedServices', 'Debugger support for MonoDevelop', 'Mono Soft Debugger Support', 'Mono Soft Debugger Support for ASP.NET', 'VsCode Debug Protocol support for MonoDevelop', 'Deployment Services Core', 'Deployment Services for Linux', 'Visual Designer Support', 'DocFood', 'Container Tools', '.NET Core Support', 'F# Language Binding', 'Gettext Translations Support', 'GTK# Visual Designer', 'MonoDevelop Hex Editor', 'ILAsm Language Binding', 'iOS development', 'Mac Development', 'MonoDevelop Mac Platform Support', 'Android development', 'IDE Extensions for developers of the Mono framework', 'Xamarin.Mac development', 'NuGet Package Management', 'NuGet Packaging', 'Performance Diagnostics of IDE', 'Refactoring Support', 'Regex Toolkit', 'MonoDevelop Source Editor', 'Test Runner', 'Text Templating', 'Unit Testing core support', 'NUnit support', 'Visual Studio for Mac Tools for Unity', 'VB.NET Language Binding', 'Version Control Support', 'Git support', 'Subversion core engine', 'Subversion support', 'Project Web References', 'Xamarin Ide Extensions', 'Xamarin Ide Extensions for Mac', 'XML Editor', 'Android Designer', 'Azure Mobile App Service', 'Azure Support', 'Xamarin Designer', 'Forms Project Support', 'Forms Previewer', 'Xamarin Ide Identity', 'Xamarin Ide Insights', 'Xamarin Inspector Support', 'Xamarin Live Player', 'Xamarin Test Cloud', 'Xamarin Test Cloud - NUnit', 'iOS Designer'

**Comment by matthewrdev** [comment]
Hi Mike, thanks for reporting this.

We naively updated our code templates from the Xamarin Forms best practices page without properly testing the code. This is the problem with making assumptions...

Looking into fixing this now.

**Comment by matthewrdev** [comment]
We've fixed our localisation code templates and are looking into the empty dialog thats showing now.

**Comment by matthewrdev** [comment]
I am no longer to reproduce this issue.

@mikehachen  If this issue persists, could you please re-open this ticket?
