### ISSUE TITLE
MFractor Import Font not working in Visual Studio for Windows

### ISSUE THREAD

**Issue by geniesoftstudios** [mfractor/mfractor-feedback#271]
There is an issue when trying to import a font using the Import Font Asset dialog within **MFractor 4.2.10**, there is no App.xaml displayed under the **Add Font Declaration** section, and it is showing **NA** under the **Result** section beside the iOS and Android projects. 
![ImportFontAssetVSW](https://user-images.githubusercontent.com/2282817/87512586-a0126c00-c6ba-11ea-8ffb-524510fe0862.png)

**Comment by matthewrdev** [comment]
@geniesoftstudios I've made significant improvements to the internals of MFractor for Windows in 4.3 that may have resolved this issue.

Can you re-test this in 4.3 and let me know if the issue persists?

**Comment by geniesoftstudios** [comment]
@matthewrdev I have tested this using version 4.3 for windows, and this issue has been resolved. Thank you🥇

**Comment by matthewrdev** [comment]
Great to hear, another issue down!
