### ISSUE TITLE
[Suggestion] Font embed failure

### ISSUE THREAD

**Issue by davidortinau** [mfractor/mfractor-feedback#275]
Mfractor does a wonderful job of showing me the fonts in my project and even previewing them (nice for icons!). BUT I made a mistake in scaffolding my project and the font files where not set as embedded resources. Agh! So I was thinking all was well b/c mfractor was showing me that it knew my fonts, but at runtime I wasn't getting the fonts and icons I expected.

It would be awesome if you could check that the fonts are indeed embedded resources if they are using the exportfont feature.

**Comment by matthewrdev** [comment]
@davidortinau This is pretty easy to do and a great addition to the font tooling. I will also include a code-fix to change the build action to `EmbeddedResource`.

**Comment by matthewrdev** [comment]
@davidortinau Done. I've added an analyser and code fix for this issue:

<img width="822" alt="Screen Shot 2020-07-19 at 8 01 16 pm" src="https://user-images.githubusercontent.com/3260473/87872317-ac6c3100-c9fa-11ea-9851-1eaa3b34c5fe.png">

**Comment by matthewrdev** [comment]
@davidortinau This will be release in MFractor 4.2.11 (due this week).
