### ISSUE TITLE
VSMac crashing when using Scaffolder

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#276]
Every now and then VS Mac crashes when I'm using the scaffolder. It's an instant, hard crash that completely closes VS Mac. Just then it happened while I was in the middle of typing a file name, but I think it happened yesterday when I hit enter.

I think this has only started happening since I updated to 8.7 preview and 4.2.10 MFractor, but it may be a conincidence because I've been used the scaffolder many, many times in the past few days.

Here's a couple of logs that show `User event: "Scaffolder"` immediately before ABRT crash. 

[Ide.2020-07-21__11-26-08.log](https://github.com/mfractor/mfractor-feedback/files/4957636/Ide.2020-07-21__11-26-08.log)

[Ide.2020-07-22__09-05-19.log](https://github.com/mfractor/mfractor-feedback/files/4957594/Ide.2020-07-22__09-05-19.log)

**Comment by matthewrdev** [comment]
@lachlanwgordon Can you try updating to 4.2.11 and see if this is resolved?

https://addins.monodevelop.com/Project/Index/300

**Comment by lachlanwgordon** [comment]
I've installed and scaffolder seems to be working fine.

I'll close this issue and reopen if it comes back.

**Comment by matthewrdev** [comment]
@lachlanwgordon, good to know. I'm concerned that updates aren't being published but we'll resolve that with the next major release.
