### ISSUE TITLE
Scaffolder on VS Windows Code Preview and Scaffold list broken

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#284]
When I open the scaffolder on VS Windows there's a little spinner that says "Please wait while MFractor loads the code preview..." but it never loads.

When I type in a file name that should trigger the list to populate e.g. "page.xaml" or "IThing" it still only has one option "Create a new class called".

<img width="1442" alt="Screen Shot 2020-07-23 at 10 41 49 am" src="https://user-images.githubusercontent.com/29908924/88243318-6a314100-ccd3-11ea-86df-6ce03bf897dc.png">

**Comment by matthewrdev** [comment]
This has been fixed and will be available in MFractor 4.3.
