### ISSUE TITLE
Enabling Mfractor causes VS to Freeze up with a blank window on next open

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#285]
If you have MFractor Disabled, and you then enable it, it will say "VS Mac will now restart", Click ok and VS closes, then it opens up with a blank window and an error that it can't open the solution.

The only way out it to force quit, VSMac and it will work fine after opening VSMac again.

I slacked you some log files a while ago when this happened, but I wasn't what caused it back then and I don't think we made any sense of it.

It's possible that this is a VS Mac issue rather than your problem, but I've tried this with a few other extensions and can't reproduce.

![Screen Shot 2020-07-24 at 1 30 06 pm](https://user-images.githubusercontent.com/29908924/88358513-97a0ec00-cdb2-11ea-8e61-e2b74ae8d82a.png)

![Screen Shot 2020-07-24 at 1 31 31 pm](https://user-images.githubusercontent.com/29908924/88358519-9a9bdc80-cdb2-11ea-8964-4906f4d67745.png)

Here's a few logs that may be useful. 

[Ide.2020-07-24__13-31-48.log](https://github.com/mfractor/mfractor-feedback/files/4970092/Ide.2020-07-24__13-31-48.log)
[Ide.2020-07-24__11-46-13.log](https://github.com/mfractor/mfractor-feedback/files/4970093/Ide.2020-07-24__11-46-13.log)
[Ide.2020-07-24__09-06-45.log](https://github.com/mfractor/mfractor-feedback/files/4970094/Ide.2020-07-24__09-06-45.log)
[Ide.2020-07-23__10-50-09.log](https://github.com/mfractor/mfractor-feedback/files/4970095/Ide.2020-07-23__10-50-09.log)

**Comment by matthewrdev** [comment]
@lachlanwgordon Is this issue still occurring?

**Comment by lachlanwgordon** [comment]
> @lachlanwgordon Is this issue still occurring?

Nope, just tested with VS Mac 8.8 and MFractor 4.4 and everything is fine.
