### ISSUE TITLE
VS Mac Runs really slow after an hour or so of use with 4.2.11

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#286]
VSMac slows down the longer it's open for, I think this only started happening yesterday. It speed up again after a restart and then deteriorates. It seems to work fine if I disable MFractor, but I haven't been very scientific about the monitoring it. 

While testing this i found issue #285 and I've attached some logs there incase they're useful.

**Comment by lachlanwgordon** [comment]
CPU is 90% idle and 25 GB free Ram, 0 swap used and all other open apps are running fine.

**Comment by matthewrdev** [comment]
@lachlanwgordon I think this is down to a build up of many, many factors and there may not be an easy fix. We have usages of Task.Run which may be exhusting the thread pool and we have a lot cases where our memory usage can be improved.

I'll need to work and make constant improvements here to clean this up. This will be an ongoing task.

**Comment by lachlanwgordon** [comment]
Fair enough. I'm happy for this to be closed if it's not an actionable item.

**Comment by matthewrdev** [comment]
@lachlanwgordon I've made some changes to 4.3 that I think will help (still many more to come):

 * Removed unnecessary usages of Task.Run. There were quite a few of these.
 * Where required, moved backgrounding threading onto our own scheduler. This affects the resources engine and analysis engine. Related to the first point.
 * Reducing the amount of `new`'s needs each analysis pass. I'm working to cache and persist as much data as possible between analysis passes now. This will be an ongoing thing for the next few weeks.

I'm interested to hear your feedback on this when 4.3 is out. Let's keep this ticket open and I'll log changes here/

**Comment by lachlanwgordon** [comment]
Thanks for the update. Keen to try it out.

**Comment by matthewrdev** [comment]
@lachlanwgordon Are you still experiencing this issue in MFractor 4.3?

**Comment by matthewrdev** [comment]
Closing this issue as its been a few months and I've done multiple passes of stability. Please reopen or create a new issue if it continues.
