### ISSUE TITLE
VS Windows issues

### ISSUE THREAD

**Issue by KAnderson** [mfractor/mfractor-feedback#287]
As shown during screen share: 
1. Image does not exist error
![image](https://user-images.githubusercontent.com/273611/88359875-8237ad80-cd31-11ea-8d8d-edb40df2545f.png)
2. Carousel IndicatorView unable to find 
![image](https://user-images.githubusercontent.com/273611/88359955-b9a65a00-cd31-11ea-8797-9ece00858725.png)
3. Binding Paths not found
![image](https://user-images.githubusercontent.com/273611/88359892-911e6000-cd31-11ea-8f75-f0bfc8d69a2e.png)
4. Manage Image Assets - not populating

##Installation Information

```
--Platform Information--
Operating System: Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.19042.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.2.11.0
Product Variant: Visual Studio For Windows
Product Variant Version: 16.0.0.0
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 456a155ffb822243ae788e1ff912fa28be4af2e3
Revision: 4363
Branch: master
Date: 12/05/2020 2:26:45 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment]
@KAnderson Thanks for the great feedback. I'll break out each of these issues into separate items so that we can track them separately as I fix them.

**Comment by matthewrdev** [comment]
@KAnderson Please see linked issues so that you can track each one individually/
