### ISSUE TITLE
[Feature Request] Scaffolder Xaml Page with Base Type

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#295]
I'm working in a project with a BasePage that should be used on every xaml page. When I use the Scaffolder it's smart enough to suggest the base type for my page when it's generating a C# file but when generating a xaml it will only use the Xamarin Forms ContentPage as Base.

<img width="1331" alt="Screen Shot 2020-08-20 at 6 05 02 pm" src="https://user-images.githubusercontent.com/29908924/90733827-67e0f780-e310-11ea-89c0-85281e7ca508.png">

It would be nice to have an item in there "Create new XAML page that derives from type {BasePage}".

In the xaml you would need an `xmlns:pages="{NameSpace}"` and set the opening and closing to `<pages:{BaseType}>`. 

In the code behind for the XAML you currently set the class to inherit from `ContentPage`, but declaring the parent in a partial is optional, so you could either make it `public partial class {NewPage} : {BasePage}` and add a using, or you could just make it `public partial class {NewPage}`. With the second option you could also use this same snippet for the ContentPage and ContentView code behinds.

**Comment by matthewrdev** [comment]
@lachlanwgordon This has been implemented and will be available in MFractor 4.3.1.
