### ISSUE TITLE
Image wizard doesn't work with F# projects

### ISSUE THREAD

**Issue by jimbobbennett** [mfractor/mfractor-feedback#3]
To reproduce - create a blank Xamarin.Forms app using F#. Try to import an image.

__Expected:__
I should be able to select the target projects and import the image to them.

__Actual:__
The F# iOS and Android apps are not in the target projects list.

<img width="723" alt="2018-04-10_16-54-20" src="https://user-images.githubusercontent.com/1710385/38568160-dd6a1e7a-3cdf-11e8-90ec-4661463a9a55.png">

**Comment by matthewrdev** [comment]
Thanks for reporting this Jim.

This is a tricky issue as MFractor uses the Roslyn project model to deduce which projects are available for importing. Because of this, F# is unfortunately unsupported as it has no Roslyn representation.

I’ll investigate how I can decouple the image wizard from roslyn and instead use the IDEs project model.

**Comment by jimbobbennett** [comment]
I imagined it might be tricky - just though it was worth reporting as I was not 100% sure on what the F# support story is. In future would you want me to report any issues around F#? Not code, obviously - but XAML in F# projects?

**Comment by matthewrdev** [comment]
Hmm, the product will fall down when F# is the backing language when MFractors XAML editor is used. In this case I may need to stop MFractors XAML editor from loading when the projects language is f#.

Report the issues to me and I’ll investigate, good to have a record of them.

**Comment by matthewrdev** [comment]
Hi @jimbobbennett,

I've done a bit more investigation into this and for the moment this isn't feasible as it'll take a huge re-engineering effort. I'm going to close this issue however I'll use it as a reference point in future when I get to adding F# support for the image wizard.
