### ISSUE TITLE
Source property of resourcedictionary

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#30]
I'm having an issue with the 'Source' property of a resourcedictionary. The program runs ok, however Mfractor displays an error.

![image](https://user-images.githubusercontent.com/13586354/48539151-9ff31500-e8b6-11e8-9304-0587d415c6c0.png)

**Comment by MBrekhof** [comment]
Additional information: I copied the xaml to the root of my project and entered this in the App.xaml, it works OK, the error displayed by MFractor stays the same. Note the '/' in the source name.
![image](https://user-images.githubusercontent.com/13586354/48585431-ee42fb00-e92c-11e8-9458-26760b85b5f5.png)

**Comment by matthewrdev** [comment]
@MBrekhof This has been fixed and will be available in the next MFractor release. I will confirm and close this issue when we have published it.

**Comment by matthewrdev** [comment]
Released in 3.6.4.
