### ISSUE TITLE
Launcher Icon Importer

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#300]
The App Icon Importer already allows developers to import single images as App Icon on iOS and Launcher Icons (using mipmap single image) to Android, which is enough for iOS but still lacks an important characteristic of Android Launcher Icons on more recent versions, the [Adaptive Icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive). 

The idea of this feature is to build upon the existing App Icon Importer to add support for importing Adaptive Icons to Android projects. The Adaptive Icons has it's own requirements and validations, but a very simplified workflow would be:

- Have 2 images as input: one for the foreground and other for the background
- The importer would validate the images for the required sizes and ratios
- The import operation should add the images resized to the specs of each density bucket, alongside with the xml drawable that describes its reference

At first my idea was to integrate those features on the existing Icon Importer dialog, but having a deep thought on it, maybe it would be better to have a separate dialog specific for this kind of import. This would avoid confusion with iOS that uses a single image. Also would avoid confusion on eligible target projects, that in a separate dialog would be only Android projects on the solution. Notice that this doesn't invalidate the current Icon Importer Features, since the user may still want to import only a single image icon to his android projects and not adopt the adaptive icons.

**Comment by lachlanwgordon** [comment]
For my adaptive icons I usually use a blank colour for my XML drawable for the background. I've also seen this in templates from Microsoft and Google so i think it's fairly common.

Could you have the option to select a foreground PNG and just enter a hex code/use a colour picker for the background?

**Comment by matthewrdev** [comment]
@lachlanwgordon @ravero This has been implemented in the Visual Studio Mac version of the app icon importer; please see the `Create Adaptive Icon` checkbox to generate the launcher_foreground images and the icon and icon_round xml files. MFractor will default the background to `@android:color/white`.
