### ISSUE TITLE
[Bug] Localizing a string in a .cs file generates incorrectly

### ISSUE THREAD

**Issue by sthewissen** [mfractor/mfractor-feedback#305]
Using the option **Replace with resx resource lookup** from code-behind (C#) generates the following line of code after putting in a key (_tabs_statistics_):

```
 statsPage.Title = $(MSBuildProjectName.Replace(" ", "_")).Resources.Resources.tabs_statistics;
```

**Comment by matthewrdev** [comment]
@sthewissen The project default namespace lookup behaviour changed in Visual Studio 8.8. I've resolved this issue and it will be in MFractor 4.4.1, released later today (AEST time).
