### ISSUE TITLE
Add App Icon appears in Nuget menu on VS Mac and in non Forms projects

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#314]
Add app Icon is an option when you right click on Dependencies which doesn't make much sense. It is also available on all projects, even if they have nothing to do with mobile. 

![Screen Shot 2020-12-29 at 8 35 19 pm](https://user-images.githubusercontent.com/29908924/103274537-0b0bf100-4a16-11eb-8395-d03b3c9b3a92.png)

The Add>Image assett seems to turn up only in appropriate places so the rules around that item might work here too.

**Comment by ravero** [comment]
Hey @lachlanwgordon, I've tried to reproduce it here in several kinds of projects, never got an Add contextual menu on the NuGet folder, also it doesn't appear for non-mobile projects.

What is the version of Visual Studio for Mac that you're using and the version of MFractor?
If you don't mind to join me on a call to try to show.

**Comment by matthewrdev** [comment]
@lachlanwgordon This should be fixed as of MFractor 4.7.7.
