### ISSUE TITLE
Trying to extract a style in WPF Xaml but nothing is being shown

### ISSUE THREAD

**Issue by slim16165** [mfractor/mfractor-feedback#320]
I've tried to follow this guide: https://docs.mfractor.com/xamarin-forms/working-with-styles/extracting-styles/
But, as you can see from the picture, nothing is shown.
![image](https://user-images.githubusercontent.com/4086781/119338282-19da9500-bc90-11eb-8fe4-2022aeed32cf.png)

##Installation Information

```
--Platform Information--
Operating System: Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.17763.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.4.7.0
Product Variant: Visual Studio For Windows
Product Variant Version: 16.0.0.0
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 456a155ffb822243ae788e1ff912fa28be4af2e3
Revision: 4600
Branch: master
Date: 06/08/2020 2:26:45 AM (UTC)
Agent: Local
Installed extensions:	
```

**Comment by matthewrdev** [comment]
Hi @slim16165, I'm reviewing our issue backlog and wanted to follow up on this issue.

MFractor does not support WPF XAML so this is the expected behaviour.
