### ISSUE TITLE
Add IntelliSense support for x:DataType

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#33]
As outlined in (DataBinding Power Moves You May Not Be Using Yet](https://blog.xamarin.com/databinding-power-moves-you-may-not-be-using-yet/), MFractor needs to support the usage of x:DataType.

This should be added as an IntelliSense attribute suggestion to all elements that have the property BindingContext.

When editing an x:DataType attribute value, MFractor should suggest all available types within the current document.

**Comment by matthewrdev** [comment]
This has been completed and will be in the next release of MFractor. Waiting until release to close this issue.

**Comment by matthewrdev** [comment]
Released in 3.6.4,

**Comment by MBrekhof** [comment]
> Released in 3.6.4,

x:Datatype is indeed recognized and a popup windows opens. However the options in the popup do not make sense to me. I would have expected something based on the ViewModel/BindingContext and now it looks more like a list of all keywords available in Xamarin Forms.

**Comment by matthewrdev** [comment]
@MBrekhof From my understanding, the x:DataType keyword is used to specify a binding context type based on the available types in the XAML file.

The behaviour implemented by MFractor is consistent with the default XAML Intellisense behaviour:

**Default IntelliSense**
<img width="969" alt="screen shot 2018-11-30 at 8 09 29 am" src="https://user-images.githubusercontent.com/3260473/49252204-7c63c900-f477-11e8-965a-2cbb799ac695.png">

**MFractor IntelliSense**
<img width="951" alt="screen shot 2018-11-30 at 8 10 01 am" src="https://user-images.githubusercontent.com/3260473/49252209-7e2d8c80-f477-11e8-9216-2951e15801c9.png">

**Comment by MBrekhof** [comment]
![screen shot 2018-11-19 at 09 15 35](https://user-images.githubusercontent.com/13586354/49289454-1ccfe280-f4a4-11e8-8a90-5945b30f923b.png)

This is what I am seeing

**Comment by matthewrdev** [comment]
@MBrekhof, that looks to be the expected behaviour.

To gain Intellisense for the view models, add an ‘xmlns:viewModels=“using:MyApp.ViewModels”’ import to the root XAML elementals.

I’m having a play with this now and there are definitely some improvements like tooltips, code analysis and namespace autoimporting that can be added.
