### ISSUE TITLE
Xaml intelisense broken

### ISSUE THREAD

**Issue by Oxoproline** [mfractor/mfractor-feedback#34]
With the latest visual studio(7.6.11) and mfractor(3.6.3) xaml intelisense is broken.
Once I disable mfractor intelisense, VS intelisense is working.

**Comment by matthewrdev** [comment]
Hi @Oxoproline, thanks for reporting the issue.

Could you please attach the IDE log files to this issue?

To get the log files, go to **Help** then **Open Log Directory**.

**Comment by matthewrdev** [comment]
Thanks @Oxoproline.

Do you have XAMLator installed also? If so, can you please disable this extension and re-enable MFractor's IntelliSense.

Also, I can see a strange error where MFractor is attempting to initialise itself twice. If you have just upgraded to the latest MFractor, also try restarting the IDE if you have not done so already.

**Comment by Oxoproline** [comment]
It was clean new installation on new macbook, so it was latest version. But now when I uninstalled mfractor and installed again, intellisense is working. I guess issue can be closed, because I am probably not able to explain and reporduce what happened.

**Comment by matthewrdev** [comment]
Ok, thanks. 👍
