### ISSUE TITLE
Add an "Add Watch" item to the right-click context menu.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#5]
As a C# developer, I would like to right-click on a symbol (variable, argument, field etc) and be able to add it to the debugger watch window.

**Comment by matthewrdev** [comment]
The **Add Watch** menu item should appear above the expression evaluator menu item.

**Comment by matthewrdev** [comment]
This actually seems pretty easy to do. Should be in next service release (3.5.1)

**Comment by matthewrdev** [comment]
Released in v3.5.3

http://addins.monodevelop.com/Stable/Mac/7.4.3/MFractor.VS.Mac.MFractor-3.05.02.mpack

**Comment by wickedw** [comment]
Great addition.

Some minor suggestions -

When performing add watch on say - 

error.Code

if "add watch" when within error portion of expression, then add watch for "error" 
if "add watch" when within .Code portion of expression, then add watch for "error.Code" (walk backwards entire expression)

Also, when adding a watch it would be great if the watch window auto-selected / focused to show your new addition.

Best
Matt

**Comment by matthewrdev** [comment]
Thanks for the feedback Matt.

I'll look into what it will take to make this possible and then I'll make the appropriate changes. Will let you know when the behaviour is done.
