### ISSUE TITLE
EventTrigger warning/runtime error incorrect

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#74]
<img width="534" alt="screen shot 2018-11-30 at 13 41 15" src="https://user-images.githubusercontent.com/13586354/49289959-c663a380-f4a5-11e8-8a9e-22a1f0d125e5.png">

I think the message is incorrect or at least confusing (runtime error) for an eventtrigger

**Comment by matthewrdev** [comment]
@MBrekhof This check has been refined and now only inspects DataTriggers and MultiTriggers. Please upgrade 3.6.7.

**Comment by MBrekhof** [comment]
works ok
