### ISSUE TITLE
Localisation Wizard has problems with &gt; in label.text

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#77]
`                  <Label Margin="10">
                        <Label.FormattedText>
                            <FormattedString>
                                <Span Text="&gt; MyAction"`
get a translation that looks like `<value>&amp;gt; MyAction </>`
the 'amp;' is not wanted as it changes the way the text is displayed ('> MyAction' should be the result, it becomes `'&gt; MyAction' `

**Comment by matthewrdev** [comment]
Thanks for reporting this @MBrekhof. I'm looking into this.

**Comment by matthewrdev** [comment]
@MBrekhof This has been fixed and will be available in v3.7 of MFractor.


![localisation-bug-fix](https://user-images.githubusercontent.com/3260473/50151295-9ecd6180-0314-11e9-8b9c-0eebda250fb3.gif)
