### ISSUE TITLE
Improve Absolute Layout XAML Intellisence

### ISSUE THREAD

**Issue by madrvojt** [mfractor/mfractor-feedback#85]
Hello,

it will be possible update Intellisence for AbsoluteLayout.LayoutBounds and AbsoluteLayout.LayoutFlags? 
(Yes, this problem Xamarin Forms IntelliSence, but mFractor fix this on another layouts and will be quicker then VS4mac team).

Screenshot there:

<img width="971" alt="screenshot1" src="https://user-images.githubusercontent.com/11706829/50011077-6992dd80-ffbb-11e8-841f-73e8211dc563.png">
<img width="969" alt="screenshot2" src="https://user-images.githubusercontent.com/11706829/50011080-6992dd80-ffbb-11e8-83a3-4b31c02c47e4.png">

Thanks!

**Comment by matthewrdev** [comment]
@madrvojt I can add it for `AbsoluteLayout.LayoutFlags` however I'll need some more clarification on expected behaviour for `AbsoluteLayout.LayoutBounds`.

Do you want `X,Y,Width,Height` Intellisense? Would a tooltip describing the appropriate input format suffice for the moment?

**Comment by matthewrdev** [comment]
@madrvojt The next release of MFractor will include better tooltips for AbsoluteLayout.LayoutBounds, XAML intellisense for LayoutFlags and analysis for LayoutBounds based on the layout flags.

This should be released early January.

**Comment by matthewrdev** [comment]
<img width="897" alt="screen shot 2018-12-18 at 9 58 21 pm" src="https://user-images.githubusercontent.com/3260473/50149794-3da38f00-0310-11e9-8d15-ec203763f92b.png">

**Comment by matthewrdev** [comment]
<img width="687" alt="screen shot 2018-12-18 at 10 00 29 pm" src="https://user-images.githubusercontent.com/3260473/50149841-5b70f400-0310-11e9-9f2d-2baca5652907.png">

**Comment by madrvojt** [comment]
Fantastic! Thanks! Looking forward to January :)
