### ISSUE TITLE
MFractor has stopped providing feedback for my XAML

### ISSUE THREAD

**Issue by lewcianci** [mfractor/mfractor-feedback#87]
Hey,

I have an issue where MFractor has stopped suggesting XAML imports and has also stopped giving useful suggestions (like replacing Image with CachedImage for instance).

When I remove MFractor and reinstall it, it picks up the license automatically from somewhere, which makes me think that the install is corrupt somehow...

How can I get it back to a working state?

EDIT: It's also stopped suggesting auto imports from related namespaces :(

![image](https://user-images.githubusercontent.com/9065229/50676145-8fe9ed00-103e-11e9-98d3-db7acadbcf8d.png)

Cached Image in this space is invalid XAML and it hasn't referenced the correct library, nor is it offering to import from the relevant namespace.

**Comment by matthewrdev** [comment]
Hi @lewcianci,

Are you still experiencing this issue? If not, please feel free to close this ticket.

Thanks!
