### ISSUE TITLE
Improve Visual Studio Macs localisation tooling

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#89]
- ResX Editor
 - ResX Manager (see https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager)
 - Export to Excel and XLIFF
 - Import from Excel and XLIFF
 - ~~For the localisation wizard, by default, insert the new key into all resx files.~~
 - Add support for google translation and azure translation services.

**Comment by orestesgaolin** [comment]
I would love to see some support for POEditor API (you can download .resx file from POEditor API: https://poeditor.com/docs/api#projects_export)

**Comment by matthewrdev** [comment]
I never knew about POEditor!

Thanks for the suggestion @orestesgaolin, keep em coming :)

**Comment by matthewrdev** [comment]
Closing this as it’s a very old ticket and we’ll create specific tickets when we start work on this feature suite. MFractor Windows is the current priority.
