### ISSUE TITLE
Add support for iOS image asset catalogs into the image manager.

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#9]
# Description
As a Xamarin developer, I'd like to import images using the image wizard and select *Image Catalogs* as an output option for iOS projects.

When the user clicks the **Generate** button, the image wizard should generate an assets json file, generate the downsized images foreach image density and then place the images inside the asset catalog.

More information on asset catalogs can be found here: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/

**Comment by orestesgaolin** [comment]
I would love to see this feature.
