### ISSUE TITLE
Static resource erroneous warning

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#91]
Since 3.72 I get some warnings about static resources, looks a bit like #45. Problem is that the warning is wrong.
<img width="648" alt="screen shot 2019-01-21 at 08 48 37" src="https://user-images.githubusercontent.com/13586354/51459739-d4bd9580-1d59-11e9-9094-653c198414e1.png">

**Comment by MBrekhof** [comment]
ok, no hurry

**Comment by matthewrdev** [comment]
The exact code analyser that checks this is:
<img width="962" alt="screen shot 2019-01-21 at 8 49 02 pm" src="https://user-images.githubusercontent.com/3260473/51466352-154efa80-1dbe-11e9-845a-3b0689f91912.png">

**Comment by MBrekhof** [comment]
problem seems to be solved
