### ISSUE TITLE
Generate view/viewmodel

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#95]
Almost perfect, using this setup:
<img width="387" alt="screenshot 2019-01-30 at 16 45 10" src="https://user-images.githubusercontent.com/13586354/51993492-43fc5d80-24af-11e9-83e2-5a418539cbe1.png">

the c# code generates ok, however the XAML is like this (and gives an error):
`<?xml version="1.0" encoding="UTF-8"?>
<MasterPage xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  x:Class="MZT.Net.ViewLayer.Pages.MijnZorgtoeslag.mfractorPage">
</MasterPage>`
should be something like this:
`<pages:MasterPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:effects="clr-namespace:MZT.ViewLayer.Effects"
    xmlns:converters="clr-namespace:MZT.ViewLayer.Converters"
    xmlns:pages="clr-namespace:MZT.ViewLayer.Pages.Framework" `

**Comment by matthewrdev** [comment]
Hi @MBrekhof,

Thanks for reporting this. Funnily enough, I’ve just spent yesterday fixing this!

A fix will be available in the next release.

**Comment by matthewrdev** [comment]
@MBrekhof This is now fixed and available in v3.7.5 of MFractor for Visual Studio Mac.

**Comment by MBrekhof** [comment]
works as advertised 👍

**Comment by matthewrdev** [comment]
🙌 Keep the bug reports coming!

**Comment by MBrekhof** [comment]
As requested some logs.
