### ISSUE TITLE
Implement font importer

### ISSUE THREAD

**Issue by matthewrdev** [mfractor/mfractor-feedback#96]
By using the font importer developers should be able to select a font on disk (ttf or otf) and import it into their Android and iOS projects.

For Android projects, it should be placed under Assets.
For iOS projects, it should be placed under Resources. Optinoally a plist entry for the font should be generated.

Developers should also be able to optionally create a XAML font family declaration like so:

```
<OnPlatform x:TypeArguments="x:String" x:Key="FontAwesomeSolid">
  <On Platform="iOS" Value="FontAwesome5ProSolid"/>
  <On Platform="Android" Value="FontAwesome5ProSolid.otf#Regular"/>
</OnPlatform>
```

To deduce the postscript name for iOS fonts, use the following console command:

```
fc-scan --format "%{postscriptname}" $fontFilePath$
```

UI Spec:
![font-importer](https://user-images.githubusercontent.com/3260473/52045321-65854400-2598-11e9-97cc-ae24fa759f9d.png)

**Comment by sthewissen** [comment]
Awesome! My suggestion (through my proxy @jfversluis) 🎉

**Comment by matthewrdev** [comment]
Well underway but sometimes I really do fail at coding:
<img width="1357" alt="screen shot 2019-02-01 at 1 51 58 pm" src="https://user-images.githubusercontent.com/3260473/52099767-a462da80-2628-11e9-83c1-b3ad9206e84e.png">

**Comment by sthewissen** [comment]
![image](https://user-images.githubusercontent.com/2419439/52119074-429a7480-2618-11e9-8c27-fe7496f03bef.png)

**Comment by matthewrdev** [comment]
Almost finished!

<img width="968" alt="screen shot 2019-02-04 at 5 51 06 pm" src="https://user-images.githubusercontent.com/3260473/52193897-82c25700-28a5-11e9-9496-1627f55627f0.png">

**Comment by matthewrdev** [comment]
A preview build is now available:
https://drive.google.com/open?id=1OWMaxJ-W_sf6sin1SB2mhLuPVl88ln8w

Please uninstall any existing MFractor installation before installing this.

**Important**
There is an issue with reliably retrieving the Postscript name of the font for iOS and so, sometimes, the generating XAML code won't work on iOS. I've tested the importer against approx 20 fonts and it works nearly all of the time now.

If you find that the XAML *doesn't* work, click on the small label below the XAML previewer to copy a terminal command to clipboard that will fetch the correct Postscript name.

**Comment by jfversluis** [comment]
Amazing Matthew, thanks!

I'm guessing I already know the answer, but is there any way of telling whenever retrieval of the Postscript name doesn't work? Then at least you could warn the user to double check it.

**Comment by matthewrdev** [comment]
Hey Gerald,

Unfortunately the postscript name lookup fails most times (😫). The current solution, prompting the user to click on that label, is the best one for the meantime.

I’ll continue investigating this though. Who knew getting the name of a font was so bloody tricky!

**Comment by sthewissen** [comment]
Yeah finding that PostScript stuff is really hard. I tried to find a way to do that on Windows and that's a huge chore that I couldn't solve. Don't quite know why it's such a chore...

**Comment by matthewrdev** [comment]
The font importer is now released and available in MFractor v3.7.6.

**Comment by matthewrdev** [comment]
I've *finally* found a way to get the postscript name using some open source code. Next release (3.7.7) will include this fix.

**Comment by jfversluis** [comment]
Of course, right after you finished it... Just out of curiosity, what did you find? Can you share it?
