### ISSUE TITLE
Show color in tooltip when hovered above hex value

### ISSUE THREAD

**Issue by orestesgaolin** [mfractor/mfractor-feedback#97]
I would be happy to see some kind of color tooltip when hovering above the hex value of the color in .xml and .axml files.

E.g. when I'm in Android XML file I can see some generic tooltips appearing when hovering on attribute values.

![image](https://user-images.githubusercontent.com/16854239/52489523-c62d0600-2bc2-11e9-8336-b57974da75a8.png)

Additional tooltips in case of C# color representations would be useful too.

![image](https://user-images.githubusercontent.com/16854239/52489650-0c826500-2bc3-11e9-8efd-34dcaad28b58.png)

**Comment by matthewrdev** [comment]
Yikes!

Yes I can definitely add this, MFractor already has a color tooltip window that can do this.

**Comment by matthewrdev** [comment]
@orestesgaolin This is now supported in the new Visual Studio editor in v8.2. Closing this issue.
