### ISSUE TITLE
Static resource definition problem

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#99]
I still have an issue with resources defined in a mergeddictionary:

<img width="823" alt="screenshot 2019-02-12 at 13 04 14" src="https://user-images.githubusercontent.com/13586354/52634644-04c70700-2ec8-11e9-8797-9a6cee239d27.png">

I created a sample project and attached it to this post
[resourcedict.zip](https://github.com/mfractor/mfractor-feedback/files/2855713/resourcedict.zip)

**Comment by matthewrdev** [comment]
Thanks for reporting this issue and for including a repro case @MBrekhof. I'll look into this today.

**Comment by matthewrdev** [comment]
This has been fixed and will be available in 3.7.8.

![image](https://user-images.githubusercontent.com/3260473/52689871-d7558880-2faf-11e9-90d9-d3aeed83bdef.png)
